### ISSUE TITLE
SentencePiece is not supported by Android

### ISSUE THREAD

**Issue by Arman-IMRSV** [deepjavalibrary/djl#1187]
## Description

I'm trying to use SentencePiece lib in Android platform, but I get the following exception, saying SentencePiece is not supported in this platform:

```
    java.lang.UnsupportedOperationException: SentencePiece is not supported by this platform
        at ai.djl.sentencepiece.jni.LibUtils.copyJniLibraryFromClasspath(LibUtils.java:77)
        at ai.djl.sentencepiece.jni.LibUtils.loadLibrary(LibUtils.java:51)
        at ai.djl.sentencepiece.SpProcessor.<clinit>(SpProcessor.java:26)
        at ai.djl.sentencepiece.SpProcessor.newInstance(SpProcessor.java:37)
        at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:49)
        at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:38)
        at com.example.myapplication.nmt.NmtMarian.predict(NmtMarian.java:97)
        at com.example.myapplication.nmt.NmtClient.predict(NmtClient.java:126)
        at com.example.myapplication.MainActivity.Translate(MainActivity.java:70)
        at com.example.myapplication.TopSectionFragment.buttonClicked(TopSectionFragment.java:57)
        at com.example.myapplication.TopSectionFragment$1.onClick(TopSectionFragment.java:47)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Any solutions? I was wondering what causes SentencePiece not to be callable in Android.

**Comment by frankfliu** [comment]
@Arman-IMRSV DJL currently doesn't support android for SentencePiece.

Currently DJL doesn't have CI to build arm based binary. We only release Android binaries for PyTorch for the time being. We hope community contributors can help support arm base releases.

You can manually build SentencePiece using Android NDK, and make some changes to LibUtils.java to load the library.

**Comment by zachgk** [comment]
For reference, someone was able to build SentencePiece for Android (not with DJL) at https://github.com/google/sentencepiece/issues/346
