### ISSUE TITLE
IdEmbedding not support PyTorchEngine

### ISSUE THREAD

**Issue by dxjjhm** [deepjavalibrary/djl#1206]
IdEmbedding userEmbedding = new IdEmbedding.Builder()
                .setDictionarySize(userCount)
                .setEmbeddingSize(64)
                .build();
        userEmbedding.initialize(manager, DataType.FLOAT32, usersND.getShape());

userEmbedding.forward(ps, new NDList(manager.create(new int[] {1,2,3,4})), true).singletonOrThrow();

Exception in thread "main" java.lang.UnsupportedOperationException: Not supported!
	at ai.djl.ndarray.BaseNDManager.invoke(BaseNDManager.java:285)
	at ai.djl.nn.transformer.MissingOps.gatherNd(MissingOps.java:31)
	at ai.djl.nn.transformer.IdEmbedding.forwardInternal(IdEmbedding.java:72)
	at ai.djl.nn.AbstractBlock.forward(AbstractBlock.java:121)
	at ai.djl.nn.Block.forward(Block.java:122)

**Comment by frankfliu** [comment]
@dxjjhm Thanks for reporting this issue. Currently DJL only implemented `gather` in MXNet. We prioritize this for PyTorch.

**Comment by dxjjhm** [comment]
Do you have some methods to get embedding-batch by input-batch

**Comment by dxjjhm** [comment]
by using  NDArrayEx Interface, I am already found a solution as follow.


  NDArray inputUserEmbedding = userInput.getNDArrayInternal()
                .embedding(userInput, userEmbeddingTable, SparseFormat.DENSE)
                .singletonOrThrow();

**Comment by frankfliu** [comment]
`gather` has been implemented in PyTorch.
