### ISSUE TITLE
Windows Server 2016 Datacenter Can't find pytorch libraries

### ISSUE THREAD

**Issue by ousinka** [deepjavalibrary/djl#1371]
## Description
Windows Server 2016 Datacenter  
Version 1607
OS Version 14393.4530 

Caused by: java.lang.UnsatisfiedLinkError: xx\.djl.ai\pytorch\1.9.1-cpu-win-x86_64\asmjit.dll: Can't find dependent libraries

### Expected Behavior
Pytorch loads normally

### Error Message

~~~
Caused by: java.lang.UnsatisfiedLinkError: xx\.djl.ai\pytorch\1.9.1-cpu-win-x86_64\asmjit.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at ai.djl.pytorch.jni.LibUtils.loadWinDependencies(LibUtils.java:148)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:91)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:50)
        ... 35 more
~~~

## How to Reproduce?

~~~
if(criteria == null) {
		criteria =
                Criteria.builder()
                        .optApplication(Application.CV.IMAGE_GENERATION)
                        .setTypes(int[].class, Image[].class)
                        .optFilter("size", "512")
                        .optArgument("truncation", 0.4f)
                        .optProgress(new ProgressBar())
                        .optEngine(PtEngine.ENGINE_NAME)
                        .build();
		}
		try {
				model = criteria.loadModel();
		} catch (ModelNotFoundException | MalformedModelException | IOException e) {
			log.error("load model error.",e);
		}
~~~

**Comment by ousinka** [comment]
DJL 0.13.0, 0.14.0  and 0.15.0-SNAPSHOT  cannot run

**Comment by frankfliu** [comment]
@ousinka 
Please install  [Visual C++ 2019 Redistributable Packages](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) and try it again.

See: https://docs.djl.ai/docs/development/troubleshooting.html#13-unsatisfiedlinkerror-issue

**Comment by ousinka** [comment]
Visual C++ installed successfully, thank you！
