### ISSUE TITLE
 face detection with paddlepaddle error

### ISSUE THREAD

**Issue by zouxiaodong** [deepjavalibrary/djl#1407]
follow the https://docs.djl.ai/jupyter/paddlepaddle/face_mask_detection_paddlepaddle.html.. get the following error

ai.djl.translate.TranslateException: java.lang.UnsupportedOperationException: This NDArray implementation does not currently support this operation
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:186)
	at ai.djl.inference.Predictor.predict(Predictor.java:123)
	at com.xx.service.FaceDetectionService.predict(FaceDetectionService.java:60)
	at com.xx.instect.service.FaceDetectionService.main(FaceDetectionService.java:32)
Caused by: java.lang.UnsupportedOperationException: This NDArray implementation does not currently support this operation
	at ai.djl.ndarray.NDArrayAdapter.getAlternativeArray(NDArrayAdapter.java:1076)
	at ai.djl.ndarray.NDArrayAdapter.getNDArrayInternal(NDArrayAdapter.java:1049)
	at ai.djl.modality.cv.util.NDImageUtils.resize(NDImageUtils.java:62)
	at ai.djl.modality.cv.util.NDImageUtils.resize(NDImageUtils.java:48)
	at ai.djl.paddlepaddle.zoo.cv.objectdetection.PpFaceDetectionTranslator.processInput(PpFaceDetectionTranslator.java:58)
	at ai.djl.paddlepaddle.zoo.cv.objectdetection.PpFaceDetectionTranslator.processInput(PpFaceDetectionTranslator.java:35)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:161)
	... 3 more

**Comment by frankfliu** [comment]
@zouxiaodong

Which os are you using? the example depends on PyTorch, which requires ubuntu 18.04 and above.

**Comment by zouxiaodong** [comment]
@frankfliu 
python code as follow works ,
def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    img = img[np.newaxis, :]
    print(img.shape)
    return img

import cv2
import numpy as np
img = cv2.imread('0214.jpg')
im_size = 960
data = preprocess(img, im_size)
scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(np.float32)
im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)
input_data = [im_shape, data,scale_factor]
input_names = predictor.get_input_names()
# print("input_names:",input_names)
for i, name in enumerate(input_names):
    input_tensor = predictor.get_input_handle(name)

    input_tensor.reshape(input_data[i].shape)
    # print("input_tensor:",img[i].shape)
    input_tensor.copy_from_cpu(input_data[i].copy())
predictor.run()

-----------------------------------------------
but the java code as follow not work,it thows exception 👍 Caused by: java.lang.UnsupportedOperationException: This NDArray implementation does not currently support this operation
	at ai.djl.ndarray.NDArrayAdapter.getAlternativeArray(NDArrayAdapter.java:1076)
	at ai.djl.ndarray.NDArrayAdapter.getNDArrayInternal(NDArrayAdapter.java:1049)
	at ai.djl.modality.cv.util.NDImageUtils.resize(NDImageUtils.java:62)
	at ai.djl.modality.cv.util.NDImageUtils.resize(NDImageUtils.java:48)
	at net.ns.instect.service.MyTranslator.processImageInput(MyTranslator.java:46)
	at net.ns.instect.service.MyTranslator.processInput(MyTranslator.java:34)
	at net.ns.instect.service.MyTranslator.processInput(MyTranslator.java:20)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:161)
	... 29 more

 NDList processImageInput(NDManager manager, Image input) {
        int imageSize = 608;
        NDArray array = input.toNDArray(manager);
        Shape shape = array.getShape();
        array = NDImageUtils.resize(array, imageSize, imageSize);
        array = NDImageUtils.normalize(array, MEAN, STD);
        array = array.expandDims(0); // make batch dimension
        array = array.transpose(2, 0, 1).flip(0); // HWC -> CHW RGB -> BGR

        NDArray im_shape = manager.create(new float[]{imageSize, imageSize}).reshape(1, 2);
        NDArray scale_factor = manager.create(new float[]{imageSize * 1.0f / shape.get(0), imageSize * 1.0f / shape.get(1)}).reshape(1, 2);
        return new NDList(im_shape, array, scale_factor);
    }

**Comment by frankfliu** [comment]
@zouxiaodong 
The jupyter notebook (both en and zh versions) works fine for me:
- https://github.com/deepjavalibrary/djl/blob/master/jupyter/paddlepaddle/face_mask_detection_paddlepaddle.ipynb
- https://github.com/deepjavalibrary/djl/blob/master/jupyter/paddlepaddle/face_mask_detection_paddlepaddle_zh.ipynb

In your python code, you use numpy to perform NDArray operations. DJL relys on engine to do ndarray operation. PaddlePaddle doesn't support NDArray operation, you have to include pytorch for the pre/post processing.

```
NDManager manager = NDManager.newBaseManager(Device.cpu(), "PyTorch");
```

**Comment by zouxiaodong** [comment]
i will try pytorch...tks
