### ISSUE TITLE
Error when trying to load Resnet model for pytorch

### ISSUE THREAD

**Issue by AbhishekBose** [deepjavalibrary/djl#1419]
I am trying to experiment with DJL using the resnet18 model downloaded from modelZoo,
Below is my scala code

`
    
    package com.abhishek.djl_test
    import ai.djl.modality.Classifications
    import ai.djl.modality.cv.transform.{CenterCrop, Normalize, Resize, ToTensor}
    import ai.djl.modality.cv.translator.ImageClassificationTranslator
    import ai.djl.modality.cv.Image
    import ai.djl.ndarray.{NDArray, NDList}
    import ai.djl.ndarray.types.DataType
    
    import ai.djl.repository.zoo.{Criteria, ZooModel}
    import ai.djl.training.util.ProgressBar
    import ai.djl.training.util.DownloadUtils
    import ai.djl.translate.{Batchifier, Translator, TranslatorContext}
    import java.nio.file.Paths
    import ai.djl._
    object ImageClassifier {

       def download_model_files() = {
        DownloadUtils.download("https://djl- 
            ai.s3.amazonaws.com/mlrepo/model/cv/image_classification/ai/djl/pytorch/resnet/0.0.1/traced_resnet18.pt.gz",
          "build/pytorch_models/resnet18/resnet18.pt",new ProgressBar())

    DownloadUtils.download("https://djl-ai.s3.amazonaws.com/mlrepo/model/cv/image_classification/ai/djl/pytorch/synset.txt",
      "build/pytorch_models/resnet18/resnet18.txt",
      new ProgressBar())
      }
      def infer() = {
        val model = createCriteria().loadModel()
        print("Model loaded successfully")
      }
    
      def createCriteria(): Criteria[Image, Classifications]= {
    
        val translator = ImageClassificationTranslator.builder
          .addTransform(new Resize(256))
          .addTransform(new CenterCrop(224, 224))
          .addTransform(new ToTensor)
          .addTransform(
            new Normalize(
              Array[Float](0.485f, 0.456f, 0.406f),
              Array[Float](0.229f, 0.224f, 0.225f)
            )
          )
          .optApplySoftmax(true)
          .optSynsetUrl("file:///Users/abhishek.bose/code/DSP_DJL_POC/build/pytorch_models/resnet18/synset.txt")
          .build
        print(translator)
         Criteria.builder
          .setTypes(classOf[Image], classOf[Classifications])
           .optModelPath(Paths.get("build/pytorch_models/resnet18"))
           .optModelName("resnet18.pt")
           .optEngine("PyTorch")
          .optOption("mapLocation", "true")
          .optTranslator(translator) // this model requires mapLocation for GPU
          .optProgress(new ProgressBar).build
      }
    
      def main(args: Array[String]): Unit = {
        download_model_files()
        infer()
      }
    }

`
Nothing fancy about this code. Just trying to load the model provided and perform some inferences with it.

As soon as I run my code I am getting the following error

`
   
        Exception in thread "main" java.util.ServiceConfigurationError: ai.djl.repository.zoo.ZooProvider: Provider 
        ai.djl.mxnet.zoo.MxZooProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at ai.djl.repository.zoo.ModelZoo.<clinit>(ModelZoo.java:36)
	at ai.djl.repository.zoo.Criteria$Builder.optModelPath(Criteria.java:501)
	at com.swiggy.djl_test.ImageClassifier$.createCriteria(ImageClassifier.scala:49)
	at com.swiggy.djl_test.ImageClassifier$.infer(ImageClassifier.scala:27)
	at com.swiggy.djl_test.ImageClassifier$.main(ImageClassifier.scala:59)
	at com.swiggy.djl_test.ImageClassifier.main(ImageClassifier.scala)
        Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 8 more

`

On attaching a debugger, I find the error to happen at this line -- >

`

        .optModelPath(Paths.get("build/pytorch_models/resnet18"))
`

I am running this code on a macOS Monterey, x86

My build.sbt is given below

`

    name := "DJL_Test"

    version := "0.1"
    
    scalaVersion := "2.11.12"
    
    libraryDependencies += "ai.djl" % "serving" % "0.12.0"
    libraryDependencies += "ai.djl.aws" % "aws-ai" % "0.14.0"
    libraryDependencies += "ai.djl.onnxruntime" % "onnxruntime-engine" % "0.14.0"
    libraryDependencies += "org.slf4j" % "log4j-over-slf4j" % "2.0.0-alpha5"
    libraryDependencies += "ai.djl.pytorch" % "pytorch-engine" % "0.14.0"
    libraryDependencies += "ai.djl.pytorch" % "pytorch-model-zoo" % "0.14.0"

`

I am python machine learning programmer and a beginner in scala and DJL. 
Looking forward to some help

**Comment by frankfliu** [comment]
@AbhishekBose  `IncompatibleClassChangeError` is a `Error` instead of `Exception`. It usually means this is a deployment related issue. 

A couple of issues related to your dependencies:
1. You should not include `serving` in your project, `serving` is a standalone application module. it should not be used in a regular project
2. version mismatch, you should use matching version between different DJL jars, we recommend you to use BOM, https://github.com/deepjavalibrary/djl/tree/master/bom
3. The correct log4j dependency should be: `log4j-slf4j-impl`, see example: https://github.com/deepjavalibrary/djl/blob/master/examples/build.gradle#L7

**Comment by AbhishekBose** [comment]
@frankfliu Updated the project to Maven and added the BOM to the pom.xml file
I was able to run the pytorch image classification inference after that.
Thanks for you help
