### ISSUE TITLE
How to load pytorch model from HuggingFace if it was saved without jit.save()?

### ISSUE THREAD

**Issue by alexshapran-as** [deepjavalibrary/djl#1488]
Hello, would you help me with PyTorch model importing?

I've downloaded Bert model https://huggingface.co/DeepPavlov/rubert-base-cased-sentence
Loaded it with pytorch-engine
But when I use:
predictor.predict(input)
I get next error:
Exception in thread "main" ai.djl.engine.EngineException: `torch::jit::load()` received a file from `torch.save()`, but `torch::jit::load()` can only load files produced by `torch.jit.save()`
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1360)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:89)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:156)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)

What should I do to avoid that error?
Thanks!

**Comment by frankfliu** [comment]
@alexshapran-as 
DJL use pytorch C++ API (libtorch), it only support jit traced model model. See: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html

Here is an example python script that download huggingface model and save it as jit script model: https://github.com/deepjavalibrary/djl-demo/blob/master/huggingface/hybrid/models/download_models.py

**Comment by alexshapran-as** [comment]
Wow! Thank you very much, I'll try that script
