### ISSUE TITLE
NPE in SpTokenizer initialization

### ISSUE THREAD

**Issue by karllessard** [deepjavalibrary/djl#1491]
## Description
If `SpTokenizer` is initialized just by passing a folder path (as specified in the Javadoc), it crashes with an NPE because code after that assumes the prefix to be non-null. See [here](https://github.com/deepjavalibrary/djl/blob/8749e4188e414a22d7de5a78bde336de3ffda756/extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java#L38) and then [here](https://github.com/deepjavalibrary/djl/blob/8749e4188e414a22d7de5a78bde336de3ffda756/extensions/sentencepiece/src/main/java/ai/djl/sentencepiece/SpTokenizer.java#L113)

### Expected Behavior
That constructor documentation should specify that only a file path can be past, which should be validated upfront.

### Error Message
Exception in thread "main" java.lang.NullPointerException
	at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at ai.djl.sentencepiece.SpTokenizer.findModelFile(SpTokenizer.java:113)
	at ai.djl.sentencepiece.SpTokenizer.loadModel(SpTokenizer.java:96)
	at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:50)
	at ai.djl.sentencepiece.SpTokenizer.<init>(SpTokenizer.java:38)

## How to Reproduce?
In Kotlin:
```kotlin
    val modelDir = Paths.get("name of a directory")
    val tokenizer = SpTokenizer(modelDir)
```

**Comment by karllessard** [comment]
I guess that should be a quick fix for you but if you prefer, I can setup my environment to prepare a PR for this

**Comment by frankfliu** [comment]
@karllessard 
Thank your for reporting this issue. It's a bug in DJL code. I created a PR to fix this bug.
