### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by wanpibaokk** [deepjavalibrary/djl#1522]
I noticed that the problem can be solved by the method mentioned on https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#for-pre-cxx11-build, but I can't fix the problem even in the pom.xml With these dependencies added, the error persists.
Can you help me see what is wrong with my dependencies?
Or what else do I need to do after setting the dependencies?
```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>ai.djl</groupId>
        <artifactId>bom</artifactId>
        <version>0.15.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>ai.djl</groupId>
      <artifactId>api</artifactId>
    </dependency>
    <!-- https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cpu-precxx11 -->
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-native-cpu-precxx11</artifactId>
      <version>1.10.0</version>
      <scope>runtime</scope>
    </dependency>

    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-jni</artifactId>
      <version>1.10.0-0.15.0</version>
      <scope>runtime</scope>
    </dependency>
```

thank you very much!

**Comment by wanpibaokk** [comment]
This is the error message in my log.
`09-Mar-2022 14:39:29.165 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [InitServlet] in web application [/IdeaMavenWeb] threw load() exception
	java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/1.10.0-cpu-linux-x86_64/libtorch_cpu.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.djl.ai/pytorch/1.10.0-cpu-linux-x86_64/libtorch_cpu.so)`

**Comment by wanpibaokk** [comment]
I don't know if it's necessary to downgrade the version, but when I try to downgrade the version to 1.6.0 or 1.7.0, I get other errors.
My dependencies are changed to this
```
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-native-cpu-precxx11</artifactId>
      <version>1.7.0</version>
    </dependency>
```
09-Mar-2022 15:43:40.298 SEVERE [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Servlet.init() for servlet [InitServlet] threw exception
	java.lang.ExceptionInInitializerError
		at com.my.web.InitServlet.init(InitServlet.java:39)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1173)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1118)
		at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1011)
		at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4952)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5266)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: ai.djl.engine.EngineException:** Failed to load PyTorch native library**
		at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:77)
		at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
		at ai.djl.engine.Engine.getEngine(Engine.java:177)
		at ai.djl.Model.newInstance(Model.java:98)
		at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:187)
		at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:149)
		at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
		at com.my.pojo.Classifier.<clinit>(Classifier.java:52)
		... 17 more
	Caused by: java.lang.IllegalStateException: Failed to download PyTorch native library
		at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:423)
		at ai.djl.pytorch.jni.LibUtils.findNativeLibrary(LibUtils.java:266)
		at ai.djl.pytorch.jni.LibUtils.getLibTorch(LibUtils.java:83)
		at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:71)
		at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:50)
		... 24 more
	Caused by: **java.io.FileNotFoundException: https://publish.djl.ai/pytorch/1.6.0/files.txt**

**Comment by wanpibaokk** [comment]
I can already use it on centos7, the reason for the error when I use 1.7 or 1.6 is that there is no correct version of jni
Below is my dependency setup
```
    <dependency>
      <groupId>ai.djl</groupId>
      <artifactId>api</artifactId>
      <version>0.15.0</version>
    </dependency>
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-engine</artifactId>
      <version>0.15.0</version>
      <scope>runtime</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cpu-precxx11 -->
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-native-cpu-precxx11</artifactId>
      <version>1.8.1</version>
      <classifier>linux-x86_64</classifier>
    </dependency>
    <!-- https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-jni -->
    <dependency>
      <groupId>ai.djl.pytorch</groupId>
      <artifactId>pytorch-jni</artifactId>
      <version>1.8.1-0.15.0</version>
    </dependency>
```
But I don't know why I can't solve this problem with pytorch-native-cpu-precxx11 of 1.10.0, And it seems that the pytorch-native-cpu-precxx11 of 1.10.0 can't add <classifier>linux-x86_64</classifier>, I don't know if this is the reason why it can't be used

**Comment by frankfliu** [comment]
@wanpibaokk 

1. DJL 0.15.0 only support PyTorch 1.8.1, 1.9.1 and 1.10.0, see: https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#installation, if you want to use 1.7.1 you must use DJL 0.10.0
2. In you 1st pom.xml file, you missed: `<classifier>linux-x86_64</classifier>`

Here is our github actions that run PyTorch on centos: https://github.com/deepjavalibrary/djl-demo/blob/master/.github/workflows/canary-centos.yml#L44

**Comment by wanpibaokk** [comment]
Thank you very much for your quick reply!
