### ISSUE TITLE
Is it possible to run DJL in Docker under Win10 and WSL2?

### ISSUE THREAD

**Issue by Dartya** [deepjavalibrary/djl#1690]
I'm trying to run DJL in Docker under Win10 and WSL2, but have some problems.

Windows version: 19044.1706
Docker Desktop version: 4.8.2 (79419)
WSL2 version: 5.10.102.1
CUDA device: RTX 2060
nVidia driver version: Game Ready 512.95

nvidia-smi powershell output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.95       Driver Version: 512.95       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:0B:00.0  On |                  N/A |
| 29%   36C    P8    12W / 190W |    996MiB /  6144MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
--//--
```

used docker base image: nvcr.io/nvidia/cuda:11.6.2-devel-ubuntu20.04
with installed  java 11, image commited

docker base image nvidia-smi output:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 512.95       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:0B:00.0  On |                  N/A |
| 29%   36C    P8    12W / 190W |   1007MiB /  6144MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

docker base image nvcc --version output:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

djl dependencies in pom.xml:

```
<!-- DJL -->
<dependency>
	<groupId>ai.djl</groupId>
	<artifactId>api</artifactId>
	<version>0.17.0</version>
</dependency>

<!-- Pytorch -->
<dependency>
	<groupId>ai.djl.pytorch</groupId>
	<artifactId>pytorch-model-zoo</artifactId>
	<version>0.17.0</version>
</dependency>

<dependency>
	<groupId>ai.djl.pytorch</groupId>
	<artifactId>pytorch-native-cu113</artifactId>
	<classifier>linux-x86_64</classifier>
	<version>1.11.0</version>
	<scope>runtime</scope>
</dependency>
```

psvm code:
```
String command = "nvidia-smi";
log.info("Executing command: {}", command);
Process proc = null;
try {
	proc = Runtime.getRuntime().exec(command);
} catch (IOException e) {
	e.printStackTrace();
}
processLog(proc);

System.out.println("GPU:");
System.out.println(Device.cpu());
System.out.println(Device.gpu().toString());

System.out.println("CUDA available: " + CudaUtils.hasCuda());
System.out.println("CUDA GPU count: " + CudaUtils.getGpuCount());

System.out.println("GPU count: " + Engine.getInstance().getGpuCount());
System.out.println("Engine: " + Engine.getInstance());
```

container stdout:
```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 512.95       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:0B:00.0  On |                  N/A |
| 29%   36C    P8    11W / 190W |    989MiB /  6144MiB |     12%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

GPU:
cpu()
gpu(0)
CUDA available: false
CUDA GPU count: 0
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:81)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:177)
        at ai.djl.engine.Engine.getInstance(Engine.java:132)
        at com.blabla.analytics.AnalyticService.main(AnalyticService.java:75)
        ... 8 more
Caused by: java.lang.IllegalStateException: Failed to download PyTorch native library
        at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:453)
        at ai.djl.pytorch.jni.LibUtils.findNativeLibrary(LibUtils.java:283)
        at ai.djl.pytorch.jni.LibUtils.getLibTorch(LibUtils.java:85)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:73)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:50)
        ... 12 more
Caused by: java.nio.file.AccessDeniedException: /home/appuser/.djl.ai/pytorch
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
        at java.base/java.nio.file.Files.createDirectories(Files.java:783)
        at ai.djl.pytorch.jni.LibUtils.downloadPyTorch(LibUtils.java:391)
        ... 16 more
```

Container using root user.

Is it possible to run DJL in Docker under Win10 and WSL2?

**Comment by frankfliu** [comment]
@Dartya 

It seems you don't have to your home folder: '/home/appuser'
Can you check in the docker if '/home/appuser' is readonly, you can try the following command manually: 
```
mkdir ~/.djl.ai/pytorch
```

You can also change DJL's cache folder: https://docs.djl.ai/docs/development/cache_management.html

By the way, Can you try CPU version of pytorch and see it that work?

**Comment by Dartya** [comment]
@frankfliu
I made a terrible mistake: there are 3 dockerfiles in my working directory, and I passed the build parameter -f not the one I edited.
The container started up, everything is fine. The only thing I encountered is that the code:
```
System.out.println("CUDA GPU count: " + CudaUtils.getGpuCount());
System.out.println("GPU count: " + Engine.getInstance().getGpuCount());
```
returned:
```
CUDA GPU count: 1
GPU count: 0
```

This was solved by adding a dependency for the pytorch engine:
```
<!-- Pytorch -->
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-model-zoo</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-native-cu113</artifactId>
    <classifier>linux-x86_64</classifier>
    <version>1.11.0</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-jni</artifactId>
    <version>1.11.0-0.17.0</version>
    <scope>runtime</scope>
</dependency>
```

and on Windows, the code from the https://d2l.djl.ai/chapter_linear-networks/linear-regression-scratch.html example worked with the following dependencies:
```
<!-- DJL -->
<dependency>
    <groupId>ai.djl</groupId>
    <artifactId>api</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl</groupId>
    <artifactId>basicdataset</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl</groupId>
    <artifactId>model-zoo</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl</groupId>
    <artifactId>examples</artifactId>
    <version>0.6.0</version>
</dependency>
<!-- MXNet -->
<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-model-zoo</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-engine</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-native-auto</artifactId>
    <version>1.8.0</version>
    <scope>runtime</scope>
</dependency>

<!-- Pytorch -->
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-model-zoo</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-native-cu113</artifactId>
    <classifier>linux-x86_64</classifier>
    <version>1.11.0</version>
    <scope>runtime</scope>
</dependency>
<dependency>
    <groupId>ai.djl.pytorch</groupId>
    <artifactId>pytorch-jni</artifactId>
    <version>1.11.0-0.17.0</version>
    <scope>runtime</scope>
</dependency>

<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.5</version>
    <scope>test</scope>
</dependency>
```

but in the container I have next output:
```
CUDA available: true
CUDA GPU count: 1
2022-06-03 13:29:31.031  WARN 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : No matching cuda flavor for linux found: cu116mkl/sm_75.
2022-06-03 13:29:31.031  INFO 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : Downloading libgfortran.so.3 ...
2022-06-03 13:29:31.213  INFO 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : Downloading libgomp.so.1 ...
2022-06-03 13:29:31.277  INFO 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : Downloading libquadmath.so.0 ...
2022-06-03 13:29:31.351  INFO 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : Downloading libopenblas.so.0 ...
2022-06-03 13:29:32.651  INFO 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : Downloading libmxnet.so ...
GPU count: 0
2022-06-03 13:29:36.685  WARN 1 --- [           main] ai.djl.mxnet.jna.LibUtils                : No matching cuda flavor for linux found: cu116mkl/sm_75.
Engine: MXNet:1.8.0, capabilities: [
        CPU_SSE,
        SIGNAL_HANDLER,
        LAPACK,
        BLAS_OPEN,
        CPU_SSE2,
        DIST_KVSTORE,
        CPU_SSE3,
        OPENMP,
        OPENCV,
        MKLDNN,
]
MXNet Library: /home/appuser/.djl.ai/mxnet/1.8.0-mkl-linux-x86_64/libmxnet.so
```

I found the following solution: https://github.com/deepjavalibrary/djl/discussions/791, but didn't understand how to use it - I can't read the libmxnet.so file. I tried adding dependency:
```
<dependency>
    <groupId>ai.djl.mxnet</groupId>
    <artifactId>mxnet-native-cu110mkl</artifactId>
    <classifier>linux-x86_64</classifier>
    <version>1.9.0</version>
    <scope>runtime</scope>
</dependency>
```
but that didn't work either.

The topic can be closed, since the pytorch should be enough for me, but if there is an opportunity to suggest what needs to be done with the MXNet, I will be extremely grateful.

**Comment by frankfliu** [comment]
@Dartya 

MXNet only support CUDA 11.2, it doesn't work on CUDA 11.6, see: https://docs.djl.ai/docs/development/dependency_management.html

**Comment by Dartya** [comment]
@frankfliu 
OK, thank you! Topic closed.
