### ISSUE TITLE
ONNX Extensions

### ISSUE THREAD

**Issue by lucaro** [deepjavalibrary/djl#1804]
I tried to get around the limitations I encountered when trying to load tf-text (https://github.com/deepjavalibrary/djl/issues/1803) by converting [the model](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3) to ONNX and trying to run it via the ONNX Runtime. This however also failed with `Fatal error: SentencepieceTokenizer is not a registered function/op`. After some googling, it appears that one would need to also load the extensions from https://github.com/microsoft/onnxruntime-extensions. Is there a way to do that in DJL?

**Comment by frankfliu** [comment]
@lucaro 
You can use `customOpLibrary` to register your library:
```
  Criteria<NDList, NDList> criteria = Criteria.builder()
          .setTypes(NDList.class, NDList.class)
          .optEngine("OnnxRuntime")
          .optModelPath(Paths.get("..."))
          .optOption("customOpLibrary", "/usr/...")
          .build();
```

**Comment by lucaro** [comment]
Great, thanks for the quick reply. After compiling the extensions from source and adding its path as a "customOpLibrary" option, the model appears to be loaded. Now I just have to figure out why it is unhappy with the input it is fed.

**Comment by lucaro** [comment]
After fixing an issue with the data pre-processing, I now have a different problem when trying to run the model. When I have TensorFlow and/or PyTorch loaded in the project in addition to the ONNX Runtime, I get one of the following errors:

```
Caused by: java.lang.ClassCastException: class ai.djl.onnxruntime.engine.OrtNDManager cannot be cast to class ai.djl.tensorflow.engine.TfNDManager (ai.djl.onnxruntime.engine.OrtNDManager and ai.djl.tensorflow.engine.TfNDManager are in unnamed module of loader 'app')
	at ai.djl.tensorflow.engine.TfNDArrayEx.getIndexer(TfNDArrayEx.java:562)
	at ai.djl.ndarray.NDArray.get(NDArray.java:523)
	at ai.djl.ndarray.NDArray.get(NDArray.java:512)
	at ai.djl.ndarray.NDArray.get(NDArray.java:557)
```
or
```
Caused by: java.lang.ClassCastException: class ai.djl.onnxruntime.engine.OrtNDManager cannot be cast to class ai.djl.pytorch.engine.PtNDManager (ai.djl.onnxruntime.engine.OrtNDManager and ai.djl.pytorch.engine.PtNDManager are in unnamed module of loader 'app')
	at ai.djl.pytorch.engine.PtNDArrayEx.getIndexer(PtNDArrayEx.java:629)
	at ai.djl.ndarray.NDArray.get(NDArray.java:523)
	at ai.djl.ndarray.NDArray.get(NDArray.java:512)
	at ai.djl.ndarray.NDArray.get(NDArray.java:557)
```
When I remove both of them and only leave ONNX, the JVM crashes with 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff84173e7e4, pid=11840, tid=27188
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [onnxruntime.dll+0xe7e4]

...

Current thread (0x000001fe102951d0):  JavaThread "main" [_thread_in_native, id=27188, stack(0x000000310b900000,0x000000310ba00000)]

Stack: [0x000000310b900000,0x000000310ba00000],  sp=0x000000310b9fed60,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [onnxruntime.dll+0xe7e4]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1742  ai.onnxruntime.OnnxTensor.close(JJ)V (0 bytes) @ 0x000001fe1fa1a463 [0x000001fe1fa1a420+0x0000000000000043]
J 1836 c2 ai.onnxruntime.OnnxTensor.close()V (12 bytes) @ 0x000001fe1fa4e868 [0x000001fe1fa4e820+0x0000000000000048]
j  ai.djl.onnxruntime.engine.OrtNDArray.close()V+11
j  ai.djl.ndarray.NDArrayAdapter.close()V+31
j  ai.djl.onnxruntime.engine.OrtNDArray.close()V+15
j  ai.djl.ndarray.BaseNDManager.close()V+44
j  ai.djl.onnxruntime.engine.OrtNDManager.close()V+1
j  ai.djl.inference.Predictor$PredictorContext.close()V+4
j  ai.djl.inference.Predictor.batchPredict(Ljava/util/List;)Ljava/util/List;+254
j  ai.djl.inference.Predictor.predict(Ljava/lang/Object;)Ljava/lang/Object;+5
...
```

The relevant code looks like this. Any idea what I'm doing wrong?
```kotlin

class UniversalSentenceEncoderMultiLingual3 : AutoCloseable {


    private val criteria = Criteria.builder()
        .optApplication(Application.NLP.TEXT_EMBEDDING)
        .setTypes(Array<String>::class.java, Array<FloatArray>::class.java)
        .optModelPath(Path.of("models/usem_v3.onnx"))
        .optTranslator(USEML3Translator())
        .optEngine("OnnxRuntime")
        .optOption("customOpLibrary", "onnxruntime_extensions/ortcustomops.dll")
        .build()

    private val model = criteria.loadModel()

    private val predictor: Predictor<Array<String>, Array<FloatArray>> = model.newPredictor()

    fun predict(inputs: List<String>): List<FloatArray> = predictor.predict(inputs.toTypedArray()).toList()

    private class USEML3Translator internal constructor() : NoBatchifyTranslator<Array<String>, Array<FloatArray>> {
        override fun processInput(ctx: TranslatorContext, inputs: Array<String>): NDList {
            val manager = ctx.ndManager
            return NDList(manager.create(inputs))
        }

        override fun processOutput(ctx: TranslatorContext, list: NDList): Array<FloatArray> {
            val result = NDList()
            val numOutputs = list.singletonOrThrow().shape[0]
            for (i in 0 until numOutputs) {
                result.add(list.singletonOrThrow()[i])
            }
            return result.stream().map { obj: NDArray -> obj.toFloatArray() }.toList().toTypedArray()
        }
    }

    override fun close() {
        predictor.close()
        model.close()
    }

}
```

**Comment by frankfliu** [comment]
For TF or PT engine issue, you can disable it by setting system properties:
```
System.setProperty("ai.djl.onnx.disable_alternative", "true");
```

The crash happen at tensor closing time. Looks like it's either been double closed or the native memory is corrupted.

Do you have a project that I can reproduce it?

**Comment by lucaro** [comment]
Hey, thanks a lot, I thought that class cast issue was probably some misconfiguration on my end.
For the other problem, I created a minimal example: https://github.com/lucaro/DJL-USELM3-Windows
Thanks a lot for having a look.

**Comment by frankfliu** [comment]
@lucaro 
I'm able to reproduce your issue. Looks like there is a bug in `OrtNDArray`, it should not support `.get(i)` operation, I will take a look into that. For the time being, you can use the following workaround:

```
    private static final class USEML3Translator implements NoBatchifyTranslator<String[], float[][]> {

        @Override
        public NDList processInput(TranslatorContext ctx, String[] inputs) {
            NDManager manager = ctx.getNDManager();
            return new NDList(manager.create(inputs));
        }

        @Override
        public float[][] processOutput(TranslatorContext ctx, NDList list) {
            NDArray array = list.singletonOrThrow();
            Shape shape = array.getShape();
            float[][] res = new float[(int)shape.get(0)][(int)shape.get(1)];
            FloatBuffer buf = array.toByteBuffer().asFloatBuffer();
            for (float[] fa : res) {
                buf.get(fa);
            }
            return res;
        }
    }
```

**Comment by frankfliu** [comment]
@lucaro 
I created a PR to fix `ClassCastException` when using `PyTorch` or TF together with OnnxRuntime. You try 0.19.0-SNAPSHOT build one the PR is merged.

If you disable `PyTorch`, your original code should throw exception, and you need to use the implementation I sent earlier.

**Comment by lucaro** [comment]
Hey,

great, thanks a lot, the above workaround works!
