### ISSUE TITLE
SemanticSegmentation example error wrong datatype

### ISSUE THREAD

**Issue by mfuchs93** [deepjavalibrary/djl#1816]
Hi everyone,

I tried to execute the SemanticSegmentation.java example. Gave me an error while processing the output in SemanticSegmentationTranslator

Exception in thread "main" ai.djl.translate.TranslateException: java.lang.IllegalArgumentException: Datatype should be INT8 or UINT8
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:189)
	at ai.djl.inference.Predictor.predict(Predictor.java:126)
	at com.example.mrisegmentationwebapp.SemanticSegmentation.predict(SemanticSegmentation.java:76)
	at com.example.mrisegmentationwebapp.SemanticSegmentation.main(SemanticSegmentation.java:52)
Caused by: java.lang.IllegalArgumentException: Datatype should be INT8 or UINT8
	at ai.djl.modality.cv.BufferedImageFactory.fromNDArray(BufferedImageFactory.java:94)
	at ai.djl.modality.cv.translator.SemanticSegmentationTranslator.processOutput(SemanticSegmentationTranslator.java:116)
	at ai.djl.modality.cv.translator.SemanticSegmentationTranslator.processOutput(SemanticSegmentationTranslator.java:36)
	at ai.djl.inference.Predictor.processOutputs(Predictor.java:225)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:183)

**Comment by frankfliu** [comment]
@mfuchs93 
Are you running with latest master branch code. This issue should have been fixed. Your line number doesn't match the latest code:

https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/SemanticSegmentationTranslator.java#L116

**Comment by frankfliu** [comment]
feel free to reopen this issue if you still have issue
