### ISSUE TITLE
ai.djl.repository.zoo.ModelNotFoundException: ModelZoo doesn't support specified engine: PyTorch

### ISSUE THREAD

**Issue by edgargao** [deepjavalibrary/djl#1850]
## Description
I will use djl SDK in Android Project.If app is a general application,it work right.If app is a system application,it will throw a excepiton,as this "ai.djl.repository.zoo.ModelNotFoundException: ModelZoo doesn't support specified engine: PyTorch".

### Expected Behavior
It can load PyTorch engine.

### Error Message
ai.djl.repository.zoo.ModelNotFoundException: ModelZoo doesn't support specified engine: PyTorch

## How to Reproduce?
script is:
Criteria criteria = Criteria.builder()
                        .optApplication(Application.CV.IMAGE_CLASSIFICATION)
                        .setTypes(NDList.class, NDList.class)
                        .optModelUrls("https://djl-ai.s3.amazonaws.com/resources/demo/pytorch/doodle_mobilenet.zip")
                        .optEngine("PyTorch")
                        .build();
ZooModel model = ModelZoo.loadModel(criteria);

AndroidManifest.xml is:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="xxx"
    android:installLocation="auto"
    android:sharedUserId="android.uid.system"> 
    <application
        android:name=".application.App"
        android:allowBackup="true"
        android:configChanges="orientation|keyboardHidden"
        android:debuggable="false"
        android:hardwareAccelerated="true"
        android:icon="@drawable/icon"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:persistent="true"
        android:roundIcon="@drawable/icon"
        android:supportsRtl="true"
        tools:ignore="GoogleAppIndexingWarning,HardcodedDebugMode">
        <activity
            android:name=".HomeActivity"
            android:launchMode="singleInstance">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="android.intent.category.HOME" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.MONKEY" />
            </intent-filter>
        </activity>
    </application>
</manifest>

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.ModelZoo.loadModel(criteria)

## What have you tried to solve it?
1.If app is a general application,it work right

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:
Android8.1

PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
@delgadofarid 

I don't have a rooted phone to test such app. Would you please provide stacktrace where the engine loading is failed?

**Comment by delgadofarid** [comment]
@frankfliu - did you mean to tag @edgargao ?

**Comment by frankfliu** [comment]
> @frankfliu - did you mean to tag @edgargao ?

Sorry, auto-complete, :)

**Comment by edgargao** [comment]
> @delgadofarid
> 
> I don't have a rooted phone to test such app. Would you please provide stacktrace where the engine loading is failed?

Hi,frankfliu.It‘s a user-defined exception,didn't have stacktrace message.It's happed in Criteria.java-loadModel() function.

**Comment by JohnDoll2023** [comment]
@edgargao What computer OS are you using? If you have mac are you on M1?

**Comment by edgargao** [comment]
> 

@JohnDoll2023  It's not a computer.I worker in an android system app.

**Comment by JohnDoll2023** [comment]
@edgargao  Right, but are you developing this android system app with a windows or mac machine?

**Comment by edgargao** [comment]
> @edgargao Right, but are you developing this android system app with a windows or mac machine?

@JohnDoll2023  I'm developing in windows 11.

**Comment by frankfliu** [comment]
@edgargao 
Can you enable debug level, and collect logs?
There should be logs related PyTorch engine loading, I suspect either failed to create cached folder or load shared library failed.

Since we don't have a rooted phone, it's hard for us to reproduce your issue.

**Comment by xyang16** [comment]
@edgargao

We use ServiceLoader to find Engine in the classpath (https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/engine/Engine.java#L64). This doesn't seems to work for system app.

A workaround for this is to manually register the Engine before loading a model.

1. Add a static model in your code.

    static {
        PtEngineProvider provider = new PtEngineProvider();
        Engine.registerEngine(provider);
    }

2. Add dependency in build.gradle.

    implementation 'ai.djl.pytorch:pytorch-engine:0.18.0'

3. Make sure you have libdjl_torch.so under your app lib folder. For example:

<img width="615" alt="Screen Shot 2022-08-09 at 10 20 36 AM" src="https://user-images.githubusercontent.com/105740670/183717222-cdb60827-ba34-456d-8f19-20b30302d26d.png">

**Comment by edgargao** [comment]
@xyang16   
Hi,Yang.I had add this static block in my code,func ModelZoo.loadModel(criteria) succesed.
But, it throw an new exception,like this:
ai.djl.engine.EngineException: No deep learning engine found.
    Please refer to https://github.com/deepjavalibrary/djl/blob/master/docs/development/troubleshooting.md for more details.
        at ai.djl.engine.Engine.getInstance(Engine.java:131)
        at ai.djl.engine.Engine.debugEnvironment(Engine.java:384)

The exception happened in this code :
NDManager ndManager = NDManager.newBaseManager();

**Comment by frankfliu** [comment]
@edgargao 
Engine class failed to initialize because of ServiceLoader doesn't work as system app. So it cannot find Engines in the class path, and default engine is always null.

NDManager.newBaseManager() call uses default engine which will also fail.

As a workaround you can create NDManager with:
```
    NDManager.newBaseManager(Device.cpu(), "PyTorch");

```

**Comment by edgargao** [comment]
@frankfliu  
Thanks,my project can right worked.

**Comment by edgargao** [comment]
@frankfliu   
I want to load model from assets dir.How can i doing?

**Comment by frankfliu** [comment]
You can load pytorch model from `InputStream`, however this is not compatible with Criteria API, you have to manually load model and translator

```
        Translator<I, O> translator = new MyTranslator();
        Model model = Model.newInstance("mode", "PyTorch");
        InputStream is = AssetManager.open("mymodel.pt");
        model.load(is);
        ZooModel<I, O> zooModel = new ZooModel<>(model, translator);
```
