### ISSUE TITLE
Can't run tensorflow multi-lingual sentence encoder

### ISSUE THREAD

**Issue by humzaiqbal** [deepjavalibrary/djl#192]
## Description
When trying to run the multi-lingual version of the Universal Sentence Encoder there is a bug where an OP type `SentencepieceOp` is not registered
### Expected Behavior
The model should run on the inputs provided

### Error Message
(Paste the complete error message, including stack trace.)
```
2020-10-05 09:13:51.718367: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:303] SavedModel load for tags { serve }; Status: success: OK. Took 1933216 microseconds.
Exception in thread "main" org.tensorflow.exceptions.TensorFlowException: Op type not registered 'SentencepieceOp' in binary running on Humzas-MacBook-Pro.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:101)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:206)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:45)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:50)
	at ai.djl.tensorflow.engine.TfModel.load(TfModel.java:95)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:142)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:162)
	at ai.securiti.privaci.detection.analyzer.topic.UniversalSentenceEncoder.predict(UniversalSentenceEncoder.java:85)
	at ai.securiti.privaci.detection.analyzer.topic.UniversalSentenceEncoder.main(UniversalSentenceEncoder.java:58)
```

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)
I am attaching a script which is modeled after this https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/UniversalSentenceEncoder.java but replaces the `modelUrl` with `"https://storage.googleapis.com/tfhub-modules/google/universal-sentence-encoder-multilingual/3.tar.gz"` [UniversalSentenceEncoder.java.zip](https://github.com/awslabs/djl/files/5328688/UniversalSentenceEncoder.java.zip)
### Steps to reproduce
(Paste the commands you ran that produced the error.)

I ran the attached script 
## What have you tried to solve it?

1. I looked up the error and it seems to be because operations in `tensorflow_text` aren't registered, I'm guessing those weren't implemented in DJL

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
[INFO ] - ----------Environment Variables----------
[INFO ] - PATH: /Users/humzaiqbal/Downloads/apache-maven-3.6.0//bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/opt/python3/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/humzaiqbal/.local/bin:/Users/humzaiqbal/Downloads/apache-maven-3.6.0/bin:/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/
[INFO ] - JAVA_HOME: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
[INFO ] - TERM: xterm-256color
[INFO ] - JAVA_MAIN_CLASS_5083: ai.djl.integration.util.DebugEnvironment
[INFO ] - LANG: en_US.UTF-8
[INFO ] - ITERM_PREV_PS1: \[\]\n\h:\W \u\n\$ \[\]
[INFO ] - LOGNAME: humzaiqbal
[INFO ] - XPC_SERVICE_NAME: 0
[INFO ] - PWD: /Users/humzaiqbal/Documents/djl
[INFO ] - TERM_PROGRAM_VERSION: 433
[INFO ] - JAVA_MAIN_CLASS_5033: org.gradle.wrapper.GradleWrapperMain
[INFO ] - SHELL: /bin/bash
[INFO ] - ITERM_ORIG_PS1: \n\h:\W \u\n\$ 
[INFO ] - TERM_PROGRAM: Apple_Terminal
[INFO ] - APP_NAME_5033: Gradle
[INFO ] - SECURITYSESSIONID: 186a7
[INFO ] - OLDPWD: /Users/humzaiqbal/Documents/djl
[INFO ] - USER: humzaiqbal
[INFO ] - APP_ICON_5033: /Users/humzaiqbal/Documents/djl/media/gradle.icns
[INFO ] - LaunchInstanceID: 91ACE051-8375-466D-8F2E-406BA163D4F6
[INFO ] - TMPDIR: /var/folders/kc/9h6dxv3s55zfnrh266jsgn2m0000gn/T/
[INFO ] - SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.s1s1rKBXJj/Listeners
[INFO ] - XPC_FLAGS: 0x0
[INFO ] - TERM_SESSION_ID: 3DB58E3A-E7F7-4B0B-B4CC-C38F894CAC2C
[INFO ] - LC_ALL: en_US.UTF-8
[INFO ] - M2_HOME: /Users/humzaiqbal/Downloads/apache-maven-3.6.0/
[INFO ] - __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
[INFO ] - HOME: /Users/humzaiqbal
[INFO ] - SHLVL: 1
[INFO ] - 
[INFO ] - ----------Hardware----------
[INFO ] - Available processors (cores): 12
[INFO ] - Byte Order: LITTLE_ENDIAN
[INFO ] - Free memory (bytes): 468419640
[INFO ] - Maximum memory (bytes): 8589934592
[INFO ] - Total memory available to JVM (bytes): 536870912
[INFO ] - Heap committed: 536870912
[INFO ] - Heap nonCommitted: 38453248
[INFO ] - GPU Count: 0
[INFO ] - Default Device: cpu()
[INFO ] - GCC: 
[INFO ] - Apple clang version 12.0.0 (clang-1200.0.32.2)
[INFO ] - Target: x86_64-apple-darwin19.6.0
[INFO ] - Thread model: posix
[INFO ] - InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by zachgk** [comment]
Similar to https://github.com/tensorflow/hub/issues/463, it seems like this model depends on [tensorflow text](https://github.com/tensorflow/text). Text is an expansion for Tensorflow that provides both native engine operators as well as some python code. We don't support Text right now, but I will change this issue to a feature request to support it

**Comment by humzaiqbal** [comment]
Great thanks, do you know if this is something that could be supported within a week or two or do you think more time would be required?

**Comment by zachgk** [comment]
@roywei Can you take a quick look at TF Text?

**Comment by jg-try** [comment]
Any news about solving this issue?

**Comment by reuschling** [comment]
Just another ping in 2022 - any news?

**Comment by reuschling** [comment]
Maybe it is possible to load the TF text with TensorFlow.loadLibrary(..) before loading the model. According to [this closed issue](https://github.com/tensorflow/java/issues/82) from the tensorflow java repo, it should be possible now to load models using tensorflow-text ops.

**Comment by reuschling** [comment]
Finally, it worked: I was able to load the multi-lingual model by loading the tensorflow_text .so files explicitly in front of loading the model:
```
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_constrained_sequence_op.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_fast_wordpiece_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_mst_ops.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_normalize_ops.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_regex_split_ops.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_sentence_breaking_ops.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_sentencepiece_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_split_merge_from_logits_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_split_merge_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_state_based_sentence_breaker_op.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_unicode_script_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_whitespace_tokenizer.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_whitespace_tokenizer_v2.so");
        TensorFlow.loadLibrary("/home/myName/.local/lib/python3.10/site-packages/tensorflow_text/python/ops/_wordpiece_tokenizer.so");
```
Maybe not all of the files has to be loaded, I will check that for me. Crucial was that the installed 'tensorflow_text' version was more or less the same than the tensorflow version used by DJL (shown with TensorFlow.version()). In my current case, the installed version under Linux/pip is '2.8.2', the DJL version is '2.8.0'.
I know this is a workaround, but maybe it helps someone, and maybe it helps enhancing DJL in this direction.

**Comment by frankfliu** [comment]
@reuschling 

Really appreciate sharing this solution. We  can add this to our document.

**Comment by siddvenk** [comment]
@reuschling thanks again for this solution. I have updated the tensorflow documentation to detail this solution https://github.com/deepjavalibrary/djl/pull/1776. This solution will be very helpful for DJL TensorFlow users!
