### ISSUE TITLE
Failed to load PyTorch native library

### ISSUE THREAD

**Issue by shinahako** [deepjavalibrary/djl#2319]
## Description
Hi team,

I'm trying to run DJL for my company. 
I have mac os and these dependencies:

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>ai.djl</groupId>
				<artifactId>bom</artifactId>
				<version>0.20.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>api</artifactId>
		</dependency>
		<dependency>
			<groupId>ai.djl.pytorch</groupId>
			<artifactId>pytorch-engine</artifactId>
			<version>0.20.0</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>ai.djl.pytorch</groupId>
			<artifactId>pytorch-model-zoo</artifactId>
			<version>0.20.0</version>
		</dependency>

### Expected Behavior
run the "BertQaInference"

### Error Message
Exception in thread "main" ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:85)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:186)
	at ai.djl.Model.newInstance(Model.java:99)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:189)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:152)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:168)
	at com.ebay.app.djl.BertQaInference.predict(BertQaInference.java:65)
	at com.ebay.app.djl.BertQaInference.main(BertQaInference.java:39)
Caused by: java.lang.UnsatisfiedLinkError: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib: dlopen(/Users/###/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib, 1): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Users/###/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:368)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:81)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54)

## Environment Info

Mac, maven, java

**Comment by frankfliu** [comment]
@shinahako 
Can you try to clean the cached and try it again:

```
rm -rf /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64
```

**Comment by shinahako** [comment]
@frankfliu hi frank, thanks for the quick response! i just ran it, and I still get the same exception

**Comment by frankfliu** [comment]
@shinahako 
We test PyTorch engine on mac daily and never seen this issue before. Can try the following:

```
git clone https://github.com/deepjavalibrary/djl-demo.git
cd djl-demo/canary
DJL_VERSION=0.20.0 PT_VERSION=1.13.0 ./gradlew run
```

**Comment by shinahako** [comment]
@frankfliu so fun having a unique issue ;D 
i'll try that, thanks!

**Comment by frankfliu** [comment]
@shinahako 
By the way, are you using mac 12, this might related to mac 11 issue, can you try PyTorch 1.12.1?

**Comment by shinahako** [comment]
I got the same issue for https://github.com/deepjavalibrary/djl-demo.git:

------------------ CUDA -----------------
[DEBUG] - cudart library not found.
GPU Count: 0

----------------- Engines ---------------
DJL version: 0.20.0
[DEBUG] - Using cache dir: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64
[DEBUG] - Loading native library: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/libiomp5.dylib
[DEBUG] - Loading native library: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/libc10.dylib
[DEBUG] - Loading native library: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/libtorch_cpu.dylib
[DEBUG] - Loading native library: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/libtorch.dylib
[DEBUG] - Loading native library: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib
Exception in thread "main" ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:85)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:186)
        at ai.djl.engine.Engine.getInstance(Engine.java:141)
        at ai.djl.engine.Engine.debugEnvironment(Engine.java:413)
        at ai.djl.canary.CanaryTest.main(CanaryTest.java:81)
Caused by: java.lang.UnsatisfiedLinkError: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib: dlopen(/Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib, 1): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Users/shnash/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:368)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:81)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54)
        ... 5 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/shnash/Library/Java/JavaVirtualMachines/openjdk-17.0.1/Contents/Home/bin/java'' finished with non-zero exit value 1
___________________________

i'll try PyTorch 1.12.1!

**Comment by frankfliu** [comment]
Can you upgrade your mac to mac 12?

I think PyTorch 1.12.1 may have the same issue, our JNI was built on mac 12.

You might want to try lower version of DJL, say DJL 0.18.0

**Comment by shinahako** [comment]
@frankfliu works now, thanks a lot! :))
