### ISSUE TITLE
Cannot download jni files libdjl_torch v1.13.1

### ISSUE THREAD

**Issue by o2e** [deepjavalibrary/djl#2391]
```java
Exception in thread "AWT-EventQueue-0" ai.djl.engine.EngineException: Cannot download jni files: https://publish.djl.ai/pytorch/1.13.1/jnilib/0.20.0/osx-x86_64/cpu/libdjl_torch.dylib
	at ai.djl.pytorch.jni.LibUtils.downloadJniLib(LibUtils.java:515)
	at ai.djl.pytorch.jni.LibUtils.findJniLibrary(LibUtils.java:252)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:80)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:54)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:186)
	at ai.djl.Model.newInstance(Model.java:99)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:189)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:152)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:168)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:141)
	at Yolo.yolo(Yolo.kt:53)

```
curl `https://publish.djl.ai/pytorch/1.13.1/jnilib/0.20.0/osx-x86_64/cpu/libdjl_torch.dylib`
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>publish/pytorch/1.13.1/jnilib/0.20.0/osx-x86_64/cpu/libdjl_torch.dylib</Key>
<RequestId>B5B42X24DREWRQ1B</RequestId>
<HostId>aHai8jMqW08RHY399cPcjm8vJgD4HVVgsmvYruhcfEl/iaTQz4g+c1lgftFO9NxS62eU9GgG3Fc=</HostId>
</Error>
```
You guys don't seem to have uploaded the `1.13.1` version of `libdjl_torch`

**Comment by frankfliu** [comment]
@o2e 

DJL 0.20.0 doesn't support PyTorch 1.13.1, you can use DJL 0.21.0-SNAPSHOT version for PyTorch 1.13.1. See:
https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#installation

I strongly recommend you to use [BOM](https://docs.djl.ai/bom/index.html). DJL's BOM will take care of dependency versions.
