### ISSUE TITLE
ai.djl.engine.EngineException: Failed to load PyTorch native library

### ISSUE THREAD

**Issue by o2e** [deepjavalibrary/djl#2392]
```java
Exception in thread "AWT-EventQueue-0" ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:85)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:186)
	at ai.djl.Model.newInstance(Model.java:99)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:189)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:152)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:168)
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:141)
	at Yolo.yolo(Yolo.kt:53)

Caused by: java.lang.UnsatisfiedLinkError: /Users/Smile/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib: dlopen(/Users/Smile/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib, 1): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
  Referenced from: /Users/Smile/.djl.ai/pytorch/1.13.0-cpu-osx-x86_64/0.20.0-libdjl_torch.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
```

System: MacOS 10.15.7 (19H2026)

It looks like my libc++.1.dylib is missing some symbols? I'm curious, why doesn't your libs come with libc++ or use a static dependency on libc++? How should I proceed now, is there any remedy, I can't upgrade my computer system version and I can't modify the system libc++. please feel free to let me know if you need to provide any information.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/24642961/218470466-d7d6b9e7-25d5-4d3c-a9f8-9bc65cef9984.png">

**Comment by frankfliu** [comment]
@o2e 

PyTorch 1.13.0 was built on mac 12, mac 10 is not supported any more. You can either upgrade your mac or use lower version of PyTorch.
