### ISSUE TITLE
Failed to load MXNet native library

### ISSUE THREAD

**Issue by kameronren** [deepjavalibrary/djl#2429]
Exception in thread "main" ai.djl.engine.EngineException: Failed to load MXNet native library
	at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:78)
	at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:186)
	at ai.djl.engine.Engine.getInstance(Engine.java:141)
	at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:116)
	at RK.vision.DjlFunctions.test(DjlFunctions.java:116)
	at RK.vision.App.main(App.java:38)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'E:\java\jdk11\bin\mxnet.dll':

**Comment by frankfliu** [comment]
Most likely your windows missing some native DLL dependencies. see: https://docs.djl.ai/docs/development/troubleshooting.html#13-unsatisfiedlinkerror-issue

**Comment by kameronren** [comment]
谢谢frankfliu，问题解决了。
