### ISSUE TITLE
ai.djl.engine.EngineException: isTuple() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by YuFighting** [deepjavalibrary/djl#2430]
The following error occurred when I used the yolov5s. torchscript. pt model
`ai.djl.engine.EngineException: isTuple() INTERNAL ASSERT FAILED at "..\\..\\aten\\src\\ATen/core/ivalue_inl.h":1101`
This is my source code

```
          BufferedImage img0 = ImageIO.read(new FileInputStream("C:/Users/25196/Desktop/dog_bike_car.jpg"));
          ImageFactory factory = ImageFactory.getInstance();
          Image img = factory.fromImage(img0);
          YoloV5Translator translator = YoloV5Translator.builder().optSynsetArtifactName("coco.names").build();
          Criteria<Image, DetectedObjects> criteria =
              Criteria.builder()
                      .setTypes(Image.class, DetectedObjects.class)
                      .optDevice(Device.cpu())
                      .optModelUrls(YoloV5Utils.YoloV5.class.getResource("/yolov5s").getPath())
                      .optModelName("yolov5s.torchscript.pt")
                      .optTranslator(translator)
                      .optEngine("PyTorch")
                      .build();
          
          try (ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria)) {
              try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                  DetectedObjects detection = predictor.predict(img);
                  System.out.println(detection);
              }
          }
```
I used spring boot and put the model under resources/yolov5s
![image](https://user-images.githubusercontent.com/126473481/221560590-8caa54e4-ee6c-4124-95c7-993457d4e99c.png)

This is all the wrong information

```
Exception in thread "main" ai.djl.translate.TranslateException: ai.djl.engine.EngineException: isTuple() INTERNAL ASSERT FAILED at "..\\..\\aten\\src\\ATen/core/ivalue_inl.h":1101, please report a bug to PyTorch. Expected Tuple but got String
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:170)
	at ai.djl.inference.Predictor.predict(Predictor.java:118)
	at cn.nhyu.yolov5_pringboot.main.main(main.java:56)
Caused by: ai.djl.engine.EngineException: isTuple() INTERNAL ASSERT FAILED at "..\\..\\aten\\src\\ATen/core/ivalue_inl.h":1101, please report a bug to PyTorch. Expected Tuple but got String
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleForward(Native Method)
	at ai.djl.pytorch.jni.IValueUtils.forward(IValueUtils.java:239)
	at ai.djl.pytorch.engine.PtSymbolBlock.forwardInternal(PtSymbolBlock.java:122)
	at ai.djl.nn.AbstractBlock.forward(AbstractBlock.java:121)
	at ai.djl.nn.Block.forward(Block.java:122)
	at ai.djl.inference.Predictor.predict(Predictor.java:123)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:163)
	... 2 more
```

**Comment by lanking520** [comment]
If tuple has to be used, you can use DJL's IValueUtils to build tuple inputs

**Comment by YuFighting** [comment]
I am using the official yolov5-6.0 yolov5s model, exported using export.py, where should I look at the input format of my model

**Comment by YuFighting** [comment]
I added the following code when initializing the data and successfully solved the problem
![image](https://user-images.githubusercontent.com/126473481/221783569-782d8827-13ba-4149-b1b4-9eff8478bfdc.png)
