### ISSUE TITLE
Not working spark example

### ISSUE THREAD

**Issue by username-still-not-available** [deepjavalibrary/djl#2579]
## Description
Tried to replicate example in: https://github.com/deepjavalibrary/djl-demo/blob/master/apache-spark/spark3.0/text/src/main/scala/com/examples/TextClassificationExample.scala

```
    val classifier = new TextClassifier()
      .setInputCol("text")
      .setOutputCol("prediction")
      .setEngine("PyTorch")
      .setModelUrl("djl://ai.djl.huggingface.pytorch/distilbert-base-uncased-finetuned-sst-2-english")
    val outputDf = classifier.classify(df)
```

### Expected Behavior
Calculate sentiment for both rows.

### Error Message
```
Failed to find a default value for batchifier
java.util.NoSuchElementException: Failed to find a default value for batchifier
	at org.apache.spark.ml.param.Params.$anonfun$getOrDefault$2(params.scala:756)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.ml.param.Params.getOrDefault(params.scala:756)
	at org.apache.spark.ml.param.Params.getOrDefault$(params.scala:753)
	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:41)
	at org.apache.spark.ml.param.Params.$(params.scala:762)
	at org.apache.spark.ml.param.Params.$$(params.scala:762)
	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:41)
```

## How to Reproduce?
```
import org.apache.spark.sql.functions.col
import org.apache.spark.sql.types.{StringType, StructField, StructType}
import org.apache.spark.sql.{Encoders, Row, SparkSession}
import org.junit.runner.RunWith
import org.scalamock.scalatest.MockFactory
import org.scalatest.BeforeAndAfterAll
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner
import ai.djl.spark.task.text.TextClassifier

@RunWith(classOf[JUnitRunner])
class Suite extends AnyFunSuite with BeforeAndAfterAll {

  var spark: SparkSession = null

  override def beforeAll(): Unit = {
    spark = SparkSession.builder()
      .appName("LocalSparkSession")
      .master("local[1]")
      .getOrCreate()
  }

  override def afterAll(): Unit = {
      spark.stop()
  }

  test("normalise title 2") {
    val df = spark.createDataFrame(Seq(
      (1, "Hello, y'all! How are you?"),
      (2, "Hello, my dog is cute")
    )).toDF("id", "text")

    // Classification
    val classifier = new TextClassifier()
      .setInputCol("text")
      .setOutputCol("prediction")
      .setEngine("PyTorch")
      .setModelUrl("djl://ai.djl.huggingface.pytorch/distilbert-base-uncased-finetuned-sst-2-english")
    val outputDf = classifier.classify(df)

    println(outputDf.first())
  }
}


```

## What have you tried to solve it?
working example:
```
    val classifier = new TextClassifier()
      .setInputCol("text")
      .setOutputCol("prediction")
      .setEngine("PyTorch")
      .setBatchifier("stack")
      .setModelUrl("djl://ai.djl.huggingface.pytorch/distilbert-base-uncased-finetuned-sst-2-english")
    val outputDf = classifier.classify(df)
```

## Environment Info

```
dependencies {
    implementation 'org.scala-lang:scala-library:2.12.5'
    implementation 'com.amazonaws:aws-java-sdk:1.12.459'
    implementation 'io.spray:spray-json_2.12:1.3.6'

    testImplementation 'org.scalatest:scalatest_2.12:3.2.14'
    testImplementation 'org.scalatestplus:junit-4-13_2.12:3.2.2.0'
    testImplementation 'org.scalamock:scalamock_2.12:5.2.0'

    compileOnly 'org.apache.spark:spark-core_2.12:3.1.2'
    compileOnly 'org.apache.spark:spark-sql_2.12:3.1.2'

    implementation "org.apache.logging.log4j:log4j-slf4j-impl:2.17.1"

    implementation platform("ai.djl:bom:0.22.1")
    implementation "ai.djl.spark:spark_2.12"
    runtimeOnly "ai.djl.pytorch:pytorch-engine"
    runtimeOnly "ai.djl.pytorch:pytorch-model-zoo"
}
```

**Comment by username-still-not-available** [comment]
@xyang16 
Which repository I need to add to 
```
repositories {
    mavenCentral()
}
```
because in maven central there is no version: 0.23.0-SNAPSHOT
https://repo.maven.apache.org/maven2/ai/djl/bom/
thank you for your advice.

**Comment by xyang16** [comment]
Please add to snapshots repository:

```
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
```

Please see the complete example in https://github.com/deepjavalibrary/djl-demo/blob/master/apache-spark/spark3.0/text/build.gradle

**Comment by username-still-not-available** [comment]
Thank you for repository. 

I am confirming that version: 
```
ai.djl:bom:0.23.0-SNAPSHOT
```
working with the original example.

```
    val classifier = new TextClassifier()
      .setInputCol("text")
      .setOutputCol("prediction")
      .setEngine("PyTorch")
      .setModelUrl("djl://ai.djl.huggingface.pytorch/distilbert-base-uncased-finetuned-sst-2-english")
    val outputDf = classifier.classify(df)
```

**Comment by xyang16** [comment]
Thanks for confirming and thanks for using DJL!

I will close the issue, feel free to reopen it if you still face issue.
