### ISSUE TITLE
无法加载yolov5的pt文件，比如yolov5s.pt文件就不可以加载成功，yolov5s.torchscript.pt文件可以加载

### ISSUE THREAD

**Issue by 201723201401012** [deepjavalibrary/djl#2627]
报错信息：

Exception in thread "main" ai.djl.engine.EngineException: PytorchStreamReader failed locating file constants.pkl: file not found
	at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method)
	at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1360)
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:89)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:156)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:166)
	at com.yolo.aim.yoloaim.controller.ObjectDetectionHbjController.predict(ObjectDetectionHbjController.java:99)
	at com.yolo.aim.yoloaim.controller.ObjectDetectionHbjController.main(ObjectDetectionHbjController.java:57)

**Comment by frankfliu** [comment]
Only torchscript model is supported. You must trace your model first. See: https://docs.djl.ai/docs/pytorch/how_to_convert_your_model_to_torchscript.html#how-to-convert-your-pytorch-model-to-torchscript
