### ISSUE TITLE
M1 Mac gets UnsatisfiedLinkError: Error looking up function 'MXNDArrayGetShapeEx64' when running InstanceSegmentation example

### ISSUE THREAD

**Issue by juliangamble** [deepjavalibrary/djl#2650]
Hi contributors, I don't want to be a downer. Thanks for your fantastic work. I'm trying to constructively engage. I look at this project and think it is great - I hope this is helpful. 

## Description
Running on an M1 Mac with MxUtils 1.9.1 compiled and compiled binary in path. 
From the examples directory running `InstanceSegmentation` with the Engine Set to Pytorch. 

### Expected Behavior
InstanceSegmentation example runs normally. 

### Error Message

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'MXNDArrayGetShapeEx64': dlsym(0xaa8062c0, MXNDArrayGetShapeEx64): symbol not found
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:620)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:596)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:582)
        at com.sun.jna.Library$Handler.invoke(Library.java:248)
        at com.sun.proxy.$Proxy17.MXNDArrayGetShapeEx64(Unknown Source)
        at ai.djl.mxnet.jna.JnaUtils.getShape(JnaUtils.java:572)
        at ai.djl.mxnet.engine.MxNDArray.getShape(MxNDArray.java:148)
        at ai.djl.nn.Parameter.setArray(Parameter.java:100)
        at ai.djl.mxnet.engine.MxModel.loadParameters(MxModel.java:229)
        at ai.djl.mxnet.engine.MxModel.load(MxModel.java:136)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:161)
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
        at ai.djl.examples.inference.InstanceSegmentation.predict(InstanceSegmentation.java:66)
        at ai.djl.examples.inference.InstanceSegmentation.main(InstanceSegmentation.java:48)
libc++abi: terminating due to uncaught exception of type dmlc::Error: [23:08:08] /Users/myuser/Documents/2023/Jun23/mxnet/src/initialize.cc:382: IOError: Bus error: 10


libc++abi: terminating due to uncaught exception of type dmlc::Error: [23:08:08] /Users/myuser/Documents/2023/Jun23/mxnet/src/initialize.cc:382: IOError: Bus error: 10



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:run'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 134
```

## How to Reproduce?
Just using vanilla unchanged code. Also compile Mxnet using XCode 14 and put on path at `/Users/myuser/.djl.ai/mxnet/1.9.1-mkl-osx-aarch64/libmxnet.dylib`

### Steps to reproduce
(Paste the commands you ran that produced the error.)
`export DJL_DEFAULT_ENGINE=PyTorch`
`./gradlew run -Dmain=ai.djl.examples.inference.InstanceSegmentation`

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
> Task :integration:debugEnv
[DEBUG] - Registering EngineProvider: XGBoost
[DEBUG] - Registering EngineProvider: LightGBM
[DEBUG] - Registering EngineProvider: OnnxRuntime
[DEBUG] - Registering EngineProvider: MXNet
[DEBUG] - Registering EngineProvider: PyTorch
[DEBUG] - Registering EngineProvider: TensorFlow
[DEBUG] - Found default engine: PyTorch
----------- System Properties -----------
gopherProxySet: false
awt.toolkit: sun.lwawt.macosx.LWCToolkit
java.specification.version: 11
sun.cpu.isalist: 
sun.jnu.encoding: UTF-8
java.class.path: /Users/myuser/Documents/2023/Jun23/djl/integration/build/classes/java/main:/Users/myuser/Documents/2023/Jun23/djl/integration/build/resources/main:/Users/myuser/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.5.0/dc98be5d5390230684a092589d70ea76a147925c/commons-cli-1.5.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.20.0/7ab4f082fd162f60afcaf2b8744a3d959feab3e8/log4j-slf4j-impl-2.20.0.jar:/Users/myuser/Documents/2023/Jun23/djl/basicdataset/build/libs/basicdataset-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/model-zoo/build/libs/model-zoo-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/testing/build/libs/testing-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/mxnet/mxnet-model-zoo/build/libs/mxnet-model-zoo-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/pytorch/pytorch-model-zoo/build/libs/pytorch-model-zoo-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/pytorch/pytorch-jni/build/libs/pytorch-jni-1.13.1-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/tensorflow/tensorflow-model-zoo/build/libs/tensorflow-model-zoo-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/ml/xgboost/build/libs/xgboost-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/ml/lightgbm/build/libs/lightgbm-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/onnxruntime/onnxruntime-engine/build/libs/onnxruntime-engine-0.23.0-SNAPSHOT.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.20.0/eb2a9a47b1396e00b5eee1264296729a70565cc0/log4j-core-2.20.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.20.0/1fe6082e660daf07c689a89c94dc0f49c26b44bb/log4j-api-2.20.0.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/mxnet/mxnet-engine/build/libs/mxnet-engine-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/pytorch/pytorch-engine/build/libs/pytorch-engine-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/tensorflow/tensorflow-engine/build/libs/tensorflow-engine-0.23.0-SNAPSHOT.jar:/Users/myuser/Documents/2023/Jun23/djl/api/build/libs/api-0.23.0-SNAPSHOT.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.testng/testng/7.7.1/8e96c60d4967a8df6dc06c3c7cf22392e3a51794/testng-7.7.1.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.36/6c62681a2f655b49963a5983b8b0950a6120ae14/slf4j-api-1.7.36.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-csv/1.10.0/8669bee353424c3223c93723291b5c3753260c1c/commons-csv-1.10.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/ml.dmlc/xgboost4j_2.12/1.7.5/5f074b329677d4e23222668597eb82de4b845a4b/xgboost4j_2.12-1.7.5.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.2/4bfc12adfe4842bf07b657f0369c4cb522955686/commons-logging-1.2.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/com.microsoft.ml.lightgbm/lightgbmlib/3.2.110/f6c85e5d7cc44d49c4544240ea5c96004680007b/lightgbmlib-3.2.110.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/com.microsoft.onnxruntime/onnxruntime/1.14.0/fb150fd72c1d2fbeea7bd53affd7c266930e3f98/onnxruntime-1.14.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.13.0/1200e7ebeedbe0d10062093f32925a912020e747/jna-5.13.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.22/691a8b4e6cf4248c3bc72c8b719337d5cb7359fa/commons-compress-1.22.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.82/a7c5fef184d238065de38f81bbc6ee50cca2e21/jcommander-1.82.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.webjars/jquery/3.6.1/d08df6250157cd2db3d9b01b11b76e9b7225083a/jquery-3.6.1.jar:/Users/myuser/Documents/2023/Jun23/djl/engines/tensorflow/tensorflow-api/build/libs/tensorflow-api-0.23.0-SNAPSHOT.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.tensorflow/tensorflow-core-api/0.5.0/6dfb7f13a9d96e6c4bd0705f122bd00d3b596b0d/tensorflow-core-api-0.5.0.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.bytedeco/javacpp/1.5.9/bee92b783ea619381df7577527f8739f778cf2f6/javacpp-1.5.9.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.22.2/fdee98b8f6abab73f146a4edb4c09e56f8278d03/protobuf-java-3.22.2.jar:/Users/myuser/.gradle/caches/modules-2/files-2.1/org.tensorflow/ndarray/0.4.0/7ab74f002dbec93944b7feb38de013afe8d4e8de/ndarray-0.4.0.jar
java.vm.vendor: Eclipse Adoptium
sun.arch.data.model: 64
user.variant: 
java.vendor.url: https://adoptium.net/
user.timezone: Australia/Sydney
os.name: Mac OS X
java.vm.specification.version: 11
sun.java.launcher: SUN_STANDARD
user.country: AU
sun.boot.library.path: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/lib:/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/lib
sun.java.command: ai.djl.integration.util.DebugEnvironment
http.nonProxyHosts: local|*.local|169.254/16|*.169.254/16
jdk.debug: release
sun.cpu.endian: little
user.home: /Users/myuser
org.gradle.appname: gradlew
user.language: en
java.specification.vendor: Oracle Corporation
java.version.date: 2023-04-18
java.home: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
ai.djl.logging.level: debug
org.gradle.internal.http.connectionTimeout: 60000
file.separator: /
java.vm.compressedOopsMode: Zero based
line.separator: 

java.specification.name: Java Platform API Specification
java.vm.specification.vendor: Oracle Corporation
java.awt.graphicsenv: sun.awt.CGraphicsEnvironment
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
ftp.nonProxyHosts: local|*.local|169.254/16|*.169.254/16
java.runtime.version: 11.0.19+7
user.name: myuser
path.separator: :
os.version: 13.4
java.runtime.name: OpenJDK Runtime Environment
file.encoding: UTF-8
java.vm.name: OpenJDK 64-Bit Server VM
java.vendor.version: Temurin-11.0.19+7
java.vendor.url.bug: https://github.com/adoptium/adoptium-support/issues
java.io.tmpdir: /var/folders/wp/hnktfy9n4rg8y67qbrkhn7x00000gn/T/
org.gradle.internal.http.socketTimeout: 120000
java.version: 11.0.19
user.dir: /Users/myuser/Documents/2023/Jun23/djl/integration
os.arch: aarch64
java.vm.specification.name: Java Virtual Machine Specification
java.awt.printerjob: sun.lwawt.macosx.CPrinterJob
sun.os.patch.level: unknown
java.library.path: /Users/myuser/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
java.vm.info: mixed mode
java.vendor: Eclipse Adoptium
java.vm.version: 11.0.19+7
sun.io.unicode.encoding: UnicodeBig
library.jansi.path: /Users/myuser/.gradle/native/jansi/1.18/osx
java.class.version: 55.0
socksNonProxyHosts: local|*.local|169.254/16|*.169.254/16
org.gradle.internal.publish.checksums.insecure: true

--------- Environment Variables ---------
NVM_RC_VERSION: 
PATH: /Users/myuser/bin/gradle-8.1.1/bin:/Users/myuser/apache-maven-3.9.2/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/envs/mxnet/bin:/Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/myuser/.cargo/bin:/Users/myuser/homebrew/bin:/Users/myuser/.yarn/bin:/Users/myuser/.config/yarn/global/node_modules/.bin:/usr/local/opt/go@1.8/bin:/Users/myuser/.local/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
CONDA_DEFAULT_ENV: mxnet
JAVA_MAIN_CLASS_55260: org.gradle.wrapper.GradleWrapperMain
CONDA_PYTHON_EXE: /Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/bin/python
CONDA_PREFIX: /Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/envs/mxnet
MAVEN_HOME: /Users/myuser/apache-maven-3.9.2
CONDA_PREFIX_1: /Users/myuser/.pyenv/versions/miniforge3-4.10.3-10
LOGNAME: myuser
TERM_PROGRAM_VERSION: 447
PWD: /Users/myuser/Documents/2023/Jun23/djl
INFOPATH: /opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:
NVM_CD_FLAGS: 
SHELL: /bin/bash
JAVA_MAIN_CLASS_55274: ai.djl.integration.util.DebugEnvironment
OLDPWD: /Users/myuser/Documents/2023/Jun23/djl
HOMEBREW_CELLAR: /opt/homebrew/Cellar
SECURITYSESSIONID: 186a5
TMPDIR: /var/folders/wp/hnktfy9n4rg8y67qbrkhn7x00000gn/T/
XPC_FLAGS: 0x0
TERM_SESSION_ID: C89926FA-5319-44AE-9E36-6362BE4E1181
NVM_IOJS_ORG_MIRROR: https://iojs.org/dist
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0xF
CONDA_PROMPT_MODIFIER: (mxnet) 
SHLVL: 1
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP: 
MANPATH: /opt/homebrew/share/man:/opt/homebrew/share/man:/opt/homebrew/share/man:/opt/homebrew/share/man:/opt/homebrew/share/man:/opt/homebrew/share/man::::::
XML_CATALOG_FILES: file:///Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/envs/mxnet/etc/xml/catalog file:///etc/xml/catalog
APP_ICON_55260: /Users/myuser/Documents/2023/Jun23/djl/media/gradle.icns
CONDA_EXE: /Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/bin/conda
JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
TERM: xterm-256color
LANG: en_AU.UTF-8
HOMEBREW_PREFIX: /opt/homebrew
GRADLE_HOME: /Users/myuser/bin/gradle-8.1.1
_CE_M: 
HOMEBREW_REPOSITORY: /opt/homebrew
NVM_NODEJS_ORG_MIRROR: https://nodejs.org/dist
APP_NAME_55260: Gradle
XPC_SERVICE_NAME: 0
DJL_DEFAULT_ENGINE: PyTorch
CONDA_SHLVL: 2
__CFBundleIdentifier: com.apple.Terminal
NVM_DIR: /Users/myuser/.nvm
TERM_PROGRAM: Apple_Terminal
USER: myuser
LaunchInstanceID: 746738AC-3E70-4508-A68B-1FD64083AA40
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.DmPg1bSvmk/Listeners
_CE_CONDA: 
GSETTINGS_SCHEMA_DIR: /Users/myuser/.pyenv/versions/miniforge3-4.10.3-10/envs/mxnet/share/glib-2.0/schemas
HOME: /Users/myuser

-------------- Directories --------------
temp directory: /var/folders/wp/hnktfy9n4rg8y67qbrkhn7x00000gn/T
DJL cache directory: /Users/myuser/.djl.ai
Engine cache directory: /Users/myuser/.djl.ai

------------------ CUDA -----------------
[DEBUG] - cudart library not found.
GPU Count: 0

----------------- Engines ---------------
DJL version: 0.23.0-SNAPSHOT
[DEBUG] - Using cache dir: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64
[DEBUG] - Loading native library: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64/libc10.dylib
[DEBUG] - Loading native library: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64/libtorch_cpu.dylib
[DEBUG] - Loading native library: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64/libtorch.dylib
[DEBUG] - Loading native library: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64/0.23.0-libdjl_torch.dylib
[INFO ] - PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
[INFO ] - Number of inter-op threads is 8
[INFO ] - Number of intra-op threads is 8
Default Engine: PyTorch:1.13.1, capabilities: [
]
PyTorch Library: /Users/myuser/.djl.ai/pytorch/1.13.1-cpu-osx-aarch64
Default Device: cpu()
PyTorch: 2
MXNet: 0
XGBoost: 10
LightGBM: 10
OnnxRuntime: 10
TensorFlow: 3

--------------- Hardware --------------
Available processors (cores): 8
Byte Order: LITTLE_ENDIAN
Free memory (bytes): 518987200
Maximum memory (bytes): 8589934592
Total memory available to JVM (bytes): 536870912
Heap committed: 536870912
Heap nonCommitted: 31195136
GCC: 
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by frankfliu** [comment]
@juliangamble 

MXNet doesn't support mac M1, you have to use PyTorch on M1.

**Comment by juliangamble** [comment]
Thanks @frankfliu this is helpful. 

You will note that I had set the environment variable above - ie:
`export DJL_DEFAULT_ENGINE=PyTorch`
`./gradlew run -Dmain=ai.djl.examples.inference.InstanceSegmentation`

Now this works for other example classes - eg `ai/djl/examples/training/TrainMnist.java` which is a delight. 
But for whatever reason - this particular example class `InstanceSegmentation` goes back to Mxnet. I'm not sure why. 

Anyway - good to know that MXNet doesn't support Mac M1.

**Comment by frankfliu** [comment]
@juliangamble 
We never have `DJL_DEFAULT_ENGINE` env var. The right way to set default engine is `-Dai.djl.default_engine=PyTorch`
