### ISSUE TITLE
paddleOCR: java.lang.IndexOutOfBoundsException: Index 96 out of bounds for length 96

### ISSUE THREAD

**Issue by biotech7** [deepjavalibrary/djl#2672]
## Description
Hi, DJL team!
I'm not sure whether it's a bug in DJL or a bug in PaddleOCR model itself or mistaken by myself. I followed this instruction to run an **English-text-recognition** model but failed with exception of "java.lang.IndexOutOfBoundsException: Index 96 out of bounds for length 96". How can I solved it?
### Expected Behavior
model should be run with no error
### Error Message
Exception` in thread "main" ai.djl.translate.TranslateException: java.lang.IndexOutOfBoundsException: Index 96 out of bounds for length 96
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:191)
	at ai.djl.inference.Predictor.predict(Predictor.java:128)
	at paddleOCR.main(paddleOCR.java:74)
Caused by: java.lang.IndexOutOfBoundsException: Index 96 out of bounds for length 96
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ai.djl.paddlepaddle.zoo.cv.wordrecognition.PpWordRecognitionTranslator.processOutput(PpWordRecognitionTranslator.java:55)
	at ai.djl.paddlepaddle.zoo.cv.wordrecognition.PpWordRecognitionTranslator.processOutput(PpWordRecognitionTranslator.java:32)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:172)

## How to Reproduce?
**follow this link:**  http://docs.djl.ai/jupyter/paddlepaddle/paddle_ocr_java.html
**model used:**   
**en_PP-OCRv3_det model:** https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar
**en_PP-OCRv3_rec model:** https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_rec_infer.tar
according to [config file](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/configs/rec/PP-OCRv3/en_PP-OCRv3_rec.yml), ppocr_keys_v1.txt file should be _en_dict.txt_
**ppocr_keys_v1.txt:** https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/en_dict.txt

## Environment Info
**OS:** win11/jdk17
**IDE:** idea

**Comment by mymagicpower** [comment]
public PpWordRecTranslator(Map<String, ?> arguments) {
        use_space_char =
                arguments.containsKey("use_space_char")
                        ? Boolean.parseBoolean(arguments.get("use_space_char").toString())
                        : true;
    }

    @Override
    public void prepare(TranslatorContext ctx) throws IOException {
        Model model = ctx.getModel();
        try (InputStream is = model.getArtifact("dict.txt").openStream()) {
            table = Utils.readLines(is, true);
            table.add(0, "blank");
            if(use_space_char){
                table.add(" ");
                table.add(" ");
            }
            else{
                table.add("");
                table.add("");
            }

        }
    }

**Comment by biotech7** [comment]
thanks for your help. one more space solved this issue.
