### ISSUE TITLE
No matching default translator found. The valid input and output classes are: (ai.djl.ndarray.NDList, ai.djl.ndarray.NDList)

### ISSUE THREAD

**Issue by juliangamble** [deepjavalibrary/djl#2682]
## Description
No clear doco or examples on setting the default translator for Object detection. 

### Expected Behavior
Reading doco or seeing an example that sets the default translator for Object Detection. 

### Error Message
```
Exception in thread "main" ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:184)
	at org.example.ObjectDetection2.predict(ObjectDetection2.java:52)
	at org.example.ObjectDetection2.main(ObjectDetection2.java:29)
Caused by: ai.djl.repository.zoo.ModelNotFoundException: No matching default translator found. The valid input and output classes are: 
	(ai.djl.ndarray.NDList, ai.djl.ndarray.NDList)

	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:91)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	... 2 more
```

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

```
package org.example;

import ai.djl.ModelException;
import ai.djl.engine.EngineException;
import ai.djl.inference.Predictor;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.TranslateException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class ObjectDetection2 {

    private static final Logger logger = LoggerFactory.getLogger(ObjectDetection2.class);
    public static final String OUTPUT_IMAGE = "detected-object.png";

    public static void main(String[] args) throws ModelException, TranslateException, IOException {
        System.out.println("Started!");

        DetectedObjects detection = ObjectDetection2.predict();
        logger.info("{}", detection);

        System.out.println("Done");
    }

    public static DetectedObjects predict() throws IOException, ModelException, TranslateException {
        Path imageFile = Paths.get("/Users/myuser/Documents/2023/Jun23/myimage.jpg");
        Image img = ImageFactory.getInstance().fromFile(imageFile);

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
                //.optTranslator(ImageClassificationTranslator.builder().setSynsetArtifactName("synset.txt").build())
                //.optTranslator(InstanceSegmentationTranslator.builder()
                //        .optSynsetArtifactName("synset.txt")
                //        .addTransform(new Resize(256,256)).build())//.setSynsetArtifactName("synset.txt").build())
                .optModelPath(Paths.get("/Users/myuser/Documents/2023/Jun23/dlj-zero-test/models")) // search models in specified path
                .optModelName("mymodel-0002.params") // specify model file prefix
                //.optBlock(resNet50)
                .optProgress(new ProgressBar())
                .build();

        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                saveBoundingBoxImage(img, detection);
                return detection;
            }
        } catch (EngineException e) {
            logger.info(e.getMessage());
        }
        throw new IOException("Sorry - didn't make it. ");
    }

    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
            throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve(OUTPUT_IMAGE);
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
        logger.info("Detected objects image has been saved in: {}", imagePath);
    }
}

```

### Steps to reproduce
(Paste the commands you ran that produced the error.)

Run the class above. 

## What have you tried to solve it?

Reading the doco here: https://github.com/deepjavalibrary/djl/blob/master/docs/load_model.md

## Environment Info

Running an M1 Mac - with the PyTorch env var set. 
`DJL_DEFAULT_ENGINE=PyTorch`
Using these libraries. 

```
<dependency>
            <groupId>ai.djl</groupId>
            <artifactId>djl-zero</artifactId>
            <version>0.22.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.22.1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
            <version>0.22.1</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.7</version>
        </dependency>
```

**Comment by frankfliu** [comment]
@juliangamble 

It looks like you are trying to load an object detection model. You need a specify a `Translator`, in this case it should something like: `SingleShotDetectionTranslator`

And also `.optModelName("mymodel-0002.params")` is problematic, you should be:

```
.optModelName("mymodel")
```

**Comment by juliangamble** [comment]
Thankyou - I've added the code in like below

```

public class ObjectDetection3 {

    private static final Logger logger = LoggerFactory.getLogger(ObjectDetection3.class);
    public static final String OUTPUT_IMAGE = "detected-object.png";
    public static final String MODEL_DIR = "/Users/user/Documents/2023/Jun23/dlj-zero-test/models";
    public static final String MODEL_NAME = "mymodel";
    public static final String FILE_TO_RUN_DETECTION_ON = "/detectionfile.jpg";

    public static void main(String[] args) throws ModelException, TranslateException, IOException {
        System.out.println("Started!");

        DetectedObjects detection = ObjectDetection3.predict();
        logger.info("{}", detection);

        System.out.println("Done");
    }

    public static DetectedObjects predict() throws IOException, ModelException, TranslateException {
        Path imageFile = Paths.get(FILE_TO_RUN_DETECTION_ON);
        Image img = ImageFactory.getInstance().fromFile(imageFile);

        File synsetFile = new File (MODEL_DIR + "/synset.txt");
        List<String> classes = new ArrayList<>();
        Scanner scan = new Scanner(new FileReader(synsetFile));
        while(scan.hasNextLine()) {
            classes.add(scan.nextLine());
        }
        
        Translator<Image, DetectedObjects> translator =
                SingleShotDetectionTranslator.builder()
                        .addTransform(new ToTensor())
                        .optSynset(classes)
                        .optThreshold(0.6f)
                        .build();
        
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
                .optTranslator(translator)
                .optModelPath(Paths.get(MODEL_DIR)) // search models in specified path
                .optModelName(MODEL_NAME) // specify model file prefix
                //.optBlock(block)
                .optProgress(new ProgressBar())
                .build();

        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                saveBoundingBoxImage(img, detection);
                return detection;
            }
        } catch (EngineException e) {
            logger.info(e.getMessage());
        }
        throw new IOException("Sorry - didn't make it. ");
    }

    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
            throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve(OUTPUT_IMAGE);
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
        logger.info("Detected objects image has been saved in: {}", imagePath);
    }
}

```

And am getting the following results:
```
Started!
Loading:     100% |████████████████████████████████████████|
[main] INFO ai.djl.pytorch.engine.PtEngine - PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 8
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 8
Exception in thread "main" java.io.FileNotFoundException: mymodel.pt file not found in: /Users/user/Documents/2023/Jun23/dlj-zero-test/models
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:76)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:161)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	at org.example.ObjectDetection3.predict(ObjectDetection3.java:88)
	at org.example.ObjectDetection3.main(ObjectDetection3.java:46)

Process finished with exit code 1
```
Do I need to add a block specification?

**Comment by juliangamble** [comment]
Thanks @frankfliu - that's helpful. 

The model was trained with DJL - so I have a file `mymodel-0002.params` sitting in the `models` directory. 


So if I add a block to the Criteria like this:
```

import ai.djl.ModelException;
import ai.djl.basicmodelzoo.cv.object_detection.ssd.SingleShotDetection;
import ai.djl.engine.EngineException;
import ai.djl.inference.Predictor;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.transform.ToTensor;
import ai.djl.modality.cv.translator.SingleShotDetectionTranslator;
import ai.djl.nn.Block;
import ai.djl.nn.SequentialBlock;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.TranslateException;
import ai.djl.translate.Translator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

public class ObjectDetection4 {

    private static final Logger logger = LoggerFactory.getLogger(ObjectDetection4.class);
    public static final String OUTPUT_IMAGE = "detected-object.png";
    public static final String MODEL_DIR = "/Users/user/Documents/2023/Jun23/dlj-zero-test/models";
    public static final String MODEL_NAME = "mymodel";
    public static final String FILE_TO_RUN_DETECTION_ON = "/imageToScan.jpg";

    public static void main(String[] args) throws ModelException, TranslateException, IOException {
        System.out.println("Started!");

        DetectedObjects detection = ObjectDetection4.predict();
        logger.info("{}", detection);

        System.out.println("Done");
    }

    public static DetectedObjects predict() throws IOException, ModelException, TranslateException {
        Path imageFile = Paths.get(FILE_TO_RUN_DETECTION_ON);
        Image img = ImageFactory.getInstance().fromFile(imageFile);

        File synsetFile = new File (MODEL_DIR + "/synset.txt");
        List<String> classes = new ArrayList<>();
        Scanner scan = new Scanner(new FileReader(synsetFile));
        while(scan.hasNextLine()) {
            classes.add(scan.nextLine());
        }

        Translator<Image, DetectedObjects> translator =
                SingleShotDetectionTranslator.builder()
                        .addTransform(new ToTensor())
                        .optSynset(classes)
                        .optThreshold(0.6f)
                        .build();

        Block block = getSsdTrainBlock(classes.size());

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
                .optTranslator(translator)
                .optModelPath(Paths.get(MODEL_DIR)) // search models in specified path
                .optModelName(MODEL_NAME) // specify model file prefix
                .optBlock(block)
                .optProgress(new ProgressBar())
                .build();

        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                saveBoundingBoxImage(img, detection);
                return detection;
            }
        } catch (EngineException e) {
            logger.info(e.getMessage());
        }
        throw new IOException("Sorry - didn't make it. ");
    }

    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
            throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve(OUTPUT_IMAGE);
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
        logger.info("Detected objects image has been saved in: {}", imagePath);
    }

    private static Block getSsdTrainBlock(int numClasses) {
        int[] numFilters = {16, 32, 64};
        SequentialBlock baseBlock = new SequentialBlock();
        for (int numFilter : numFilters) {
            baseBlock.add(SingleShotDetection.getDownSamplingBlock(numFilter));
        }

        List<List<Float>> sizes = new ArrayList<>();
        List<List<Float>> ratios = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            ratios.add(Arrays.asList(1f, 2f, 0.5f));
        }
        sizes.add(Arrays.asList(0.2f, 0.272f));
        sizes.add(Arrays.asList(0.37f, 0.447f));
        sizes.add(Arrays.asList(0.54f, 0.619f));
        sizes.add(Arrays.asList(0.71f, 0.79f));
        sizes.add(Arrays.asList(0.88f, 0.961f));

        return SingleShotDetection.builder()
                .setNumClasses(numClasses)
                .setNumFeatures(3)
                .optGlobalPool(true)
                .setRatios(ratios)
                .setSizes(sizes)
                .setBaseNetwork(baseBlock)
                .build();
    }
}
```
Then I get 
``Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)``
As in the process terminated inexplicably. 

Is there a way I can get more information on what is going on?

**Comment by juliangamble** [comment]
Thanks @frankfliu  - I've incorporated that - using a resnet builder. I'm running it and then it is crashing. I'm looking for a way to get more information about what to do next. 

```

public class ObjectDetection4 {

    private static final Logger logger = LoggerFactory.getLogger(ObjectDetection4.class);
    public static final String OUTPUT_IMAGE = "detected-object.png";
    public static final String MODEL_DIR = "/Users/user/Documents/2023/Jun23/dlj-zero-test/models";
    public static final String MODEL_NAME = "mymodel";
    public static final String FILE_TO_RUN_DETECTION_ON = "imageToScan.jpg";

    public static void main(String[] args) throws ModelException, TranslateException, IOException {
        System.out.println("Started!");

        DetectedObjects detection = ObjectDetection4.predict();
        logger.info("{}", detection);

        System.out.println("Done");
    }

    public static DetectedObjects predict() throws IOException, ModelException, TranslateException {
        Path imageFile = Paths.get(FILE_TO_RUN_DETECTION_ON);
        Image img = ImageFactory.getInstance().fromFile(imageFile);

        File synsetFile = new File (MODEL_DIR + "/synset.txt");
        List<String> classes = new ArrayList<>();
        Scanner scan = new Scanner(new FileReader(synsetFile));
        while(scan.hasNextLine()) {
            classes.add(scan.nextLine());
        }

        Translator<Image, DetectedObjects> translator =
                SingleShotDetectionTranslator.builder()
                        .addTransform(new ToTensor())
                        .optSynset(classes)
                        .optThreshold(0.6f)
                        .build();
        

        Block block = //resnet50
                ResNetV1.builder()
                        .setImageShape(new Shape(3, 32, 32))
                        .setNumLayers(50)
                        .setOutSize(10)
                        .build();

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
                .optTranslator(translator)
                .optModelPath(Paths.get(MODEL_DIR)) // search models in specified path
                .optModelName(MODEL_NAME) // specify model file prefix
                .optBlock(block)
                .optProgress(new ProgressBar())
                .build();

        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                saveBoundingBoxImage(img, detection);
                return detection;
            }
        } catch (EngineException e) {
            logger.info(e.getMessage());
        }
        throw new IOException("Sorry - didn't make it. ");
    }

    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
            throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve(OUTPUT_IMAGE);
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
        logger.info("Detected objects image has been saved in: {}", imagePath);
    }
}
```


I get the following result:
```
Started!
Loading:     100% |████████████████████████████████████████|
[main] INFO ai.djl.pytorch.engine.PtEngine - PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 8
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 8

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

**Comment by juliangamble** [comment]
Thanks for all your help.
