### ISSUE TITLE
Loading .params trained model tries to load PyTorch model mlp.pt

### ISSUE THREAD

**Issue by juliangamble** [deepjavalibrary/djl#2692]
## Description
I've trained a model on my dataset. (`mlp-0002.params`) Now I want to load it using the `Criteria` class.  This leads to an error:
```
Exception in thread "main" java.io.FileNotFoundException: mlp.pt file not found in: 
/Users/user/Documents/2023/Jun23/dlj-zero-test/build/mlp
```
Note - I'm on a mac - so I have `DJL_DEFAULT_ENGINE=PyTorch` enabled. 

### Expected Behavior
The Criteria suggests loading up the `mlp-0002.params`file. 

### Error Message
```
[main] INFO ai.djl.pytorch.engine.PtEngine - PyTorch graph executor optimizer is enabled, this may impact your inference latency and throughput. See: https://docs.djl.ai/docs/development/inference_performance_optimization.html#graph-executor-optimization
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of inter-op threads is 8
[main] INFO ai.djl.pytorch.engine.PtEngine - Number of intra-op threads is 8
Exception in thread "main" java.io.FileNotFoundException: mlp.pt file not found in: /Users/user/Documents/2023/Jun23/dlj-zero-test/build/mlp
	at ai.djl.pytorch.engine.PtModel.load(PtModel.java:76)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:161)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	at org.example.ObjectDetection7.predict(ObjectDetection7.java:103)
	at org.example.ObjectDetection7.main(ObjectDetection7.java:48)
```

## How to Reproduce?
`pom.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>dlj-zero-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>

        <!-- https://mvnrepository.com/artifact/ai.djl/djl-zero -->
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>djl-zero</artifactId>
            <version>0.22.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.22.1</version>
            <scope>runtime</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-model-zoo -->
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
            <version>0.22.1</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.7</version>
        </dependency>


    </dependencies>

</project>
```
`ObjectDetection7.java`
```
package org.example;

import ai.djl.Application;
import ai.djl.Model;
import ai.djl.ModelException;
import ai.djl.basicdataset.cv.classification.ImageFolder;
import ai.djl.basicmodelzoo.basic.Mlp;
import ai.djl.engine.Engine;
import ai.djl.inference.Predictor;
import ai.djl.modality.Classifications;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.transform.ToTensor;
import ai.djl.modality.cv.translator.SingleShotDetectionTranslator;
import ai.djl.modality.cv.util.NDImageUtils;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDList;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.training.util.ProgressBar;
import ai.djl.translate.Batchifier;
import ai.djl.translate.TranslateException;
import ai.djl.translate.Translator;
import ai.djl.translate.TranslatorContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.example.ImageClassification.getDataset;
import static org.example.Training6.IMAGE_HEIGHT;
import static org.example.Training6.IMAGE_WIDTH;

public class ObjectDetection7 {
    private static final Logger logger = LoggerFactory.getLogger(ObjectDetection7.class);

    public static final String FILE_TO_RUN_DETECTION_ON = "/Users/user/Documents/2023/Jun23/djl/examples/src/test/resources/image.jpg";

    private ObjectDetection7() {
    }

    public static void main(String[] args) throws ModelException, TranslateException, IOException {
        DetectedObjects detection = ObjectDetection7.predict();
        logger.info("{}", detection);
    }

    public static DetectedObjects predict() throws IOException, ModelException, TranslateException {
        Path imageFile = Paths.get(FILE_TO_RUN_DETECTION_ON);
        Image img = ImageFactory.getInstance().fromFile(imageFile);

        ImageFolder dataset = getDataset();
        List<String> classes = dataset.getSynset();

        Translator<Image, DetectedObjects> translator =
                SingleShotDetectionTranslator.builder()
                        .addTransform(new ToTensor())
                        .optSynset(classes)
                        //.optThreshold(0.6f)
                        .optThreshold(0.2f)
                        .build();

        Criteria<Image, DetectedObjects> criteria =
                Criteria.builder()
                        .optApplication(Application.CV.OBJECT_DETECTION)
                        .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
                        .optTranslator(translator)
                        .setTypes(Image.class, DetectedObjects.class)
                        .optModelPath(Paths.get("build/mlp"))

                        .optEngine(Engine.getDefaultEngineName())
                        .optProgress(new ProgressBar())
                        .build();


        try (ZooModel<Image, DetectedObjects> model = criteria.loadModel()) {
            try (Predictor<Image, DetectedObjects> predictor = model.newPredictor()) {
                DetectedObjects detection = predictor.predict(img);
                saveBoundingBoxImage(img, detection);
                return detection;
            }
        }
    }

    private static void saveBoundingBoxImage(Image img, DetectedObjects detection)
            throws IOException {
        Path outputDir = Paths.get("build/output");
        Files.createDirectories(outputDir);

        img.drawBoundingBoxes(detection);

        Path imagePath = outputDir.resolve("detected-image.png");
        // OpenJDK can't save jpg with alpha channel
        img.save(Files.newOutputStream(imagePath), "png");
        logger.info("Detected objects image has been saved in: {}", imagePath);
    }



}

```

### Steps to reproduce
(Paste the commands you ran that produced the error.)
In IntelliJ I have run the class with the environment variable `DJL_DEFAULT_ENGINE=PyTorch` and `JAVA_HOME=`

## What have you tried to solve it?

1. Based on the advice here: I tried to give it a name https://github.com/deepjavalibrary/djl/issues/2686#issuecomment-1616767582
2. I looked at the class `PTModel` to see if there was a way to save as a PyTorch model. There wasn't. 
3. I tried setting the engine with `.optEngine("MXNet")` but that blew up because I was on an M1 mac. 

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by juliangamble** [comment]
Figured it out.
