### ISSUE TITLE
Memory for

### ISSUE THREAD

**Issue by AndyDPesspd** [deepjavalibrary/djl#2800]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment Info

Please run the command `./gradlew debugEnv` from the root directory of DJL (if necessary, clone DJL first). It will output information about your system, environment, and installation that can help us debug your issue. Paste the output of the command below:

```
PASTE OUTPUT HERE
```

**Comment by frankfliu** [comment]
@AndyDPesspd 

The code looks fine. Can you show how you invoke `detect()` function?
Are you creating `Yolov5()` object on each inference?

**Comment by AndyDPesspd** [comment]
I hold and use Yolov5 as a member variable, and I don't create it repeatedly. Here's a simple test code for me, but there's also a memory leak problem. That's why I think it's DJL's own problem.

```
public class jarTest {
    public static void main(String[] args) throws ModelNotFoundException, MalformedModelException, IOException {
        Yolov5 yolov5 = new Yolov5();
        for (int i = 0; i < 1000000; i++ ) {
            System.out.println(i);
            yolov5.detect("fff", "9", "D:\\jarTest\\s1_pack1_pt13_v0.jpg",
                    "D:\\");

            //yolov5.predictor.close();
           // yolov5.predictor = yolov5.model.newPredictor();
        }
    }
}
```

And I found that if I closed the predictor after each inference and then turned it back on, the memory leak was slower. If the model is disabled after each inference and then restarted, the memory leakage speed is greatly reduced. But i don't create Yolov5() object repeatedly.

**Comment by AndyDPesspd** [comment]
And I've tested several versions of pytorch-jni, all of which have memory leaks.
1.13.0-0.20.0
1.10.0-0.15.0
1.11.0-0.21.0
1.11.0-0.19.0
1.13.1-0.21.0
2.01.0-0.23.0

**Comment by AndyDPesspd** [comment]
I pulled all the variables out and fixed them, and I ran predict continuously (just run this line of code: `results = this.predictor.predict(img);` ), and there was still a memory leak, which made me confirm that it was djl's own problem.

**Comment by AndyDPesspd** [comment]
@frankfliu

**Comment by AndyDPesspd** [comment]
> @AndyDPesspd
> 
> The code looks fine. Can you show how you invoke `detect()` function? Are you creating `Yolov5()` object on each inference?

Please check my reply above. Thank you

**Comment by frankfliu** [comment]
I tested the following code, and I didn't see any memory leak:

```
public class Yolov5 {

    public static void main(String[] args) throws ModelException, IOException, TranslateException {
        String home = System.getProperty("user.home");
        Path imgPath = Paths.get(home, "sample/kitten.jpg");
        Yolov5 yolov5 = new Yolov5();
        for (int i = 0; i < 10000; i++) {
            System.out.println(i);
            yolov5.detect(imgPath);
        }
    }

    private Predictor<Image, DetectedObjects> predictor;

    public Yolov5() throws IOException, ModelException {
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optModelUrls("djl://ai.djl.pytorch/yolov5s")
                .optTranslatorFactory(new YoloV5TranslatorFactory())
                .optEngine("PyTorch")
                .build();
        ZooModel<Image, DetectedObjects> model = criteria.loadModel();
        predictor = model.newPredictor();
    }

    public void detect(Path imgPath) throws IOException, TranslateException {
        Image img = ImageFactory.getInstance().fromFile(imgPath);
        DetectedObjects results = predictor.predict(img);
    }
}
```

I set JVM options as `-Xmx1g -Xms1g` to limit the JVM heap, and the system memory consumption is stable at 1.48G - 1.51 G.

**Comment by frankfliu** [comment]
If you wan to use openCV to process image, you can use opencv extension: https://github.com/deepjavalibrary/djl/tree/master/extensions/opencv

**Comment by AndyDPesspd** [comment]
@frankfliu Now, however, it brings new problems. The detection precision decreases and an empty array is returned.

**Comment by AndyDPesspd** [comment]
ok，i already know the cause and find a temporary solution. best regards.

**Comment by AndyDPesspd** [comment]
> @AndyDPesspd
> 
> I tried with DJL OpenCV extension. no memory leak as well. So the memory leak must related to your OpenCV code somewhere.
> 
> Can you elaborate a bit more about `translator.optSynsetArtifactName()`? What the problem are you facing? In our test we get the exact the same result no matter use OpenCV or not.

Yes, the OpenCV is compiled by myself. When i remove the OpenCV, no more memory leaks. And If.optSynsetArtifactName("result.names") is used, an empty array may be output, as shown in the preceding figure.

**Comment by AndyDPesspd** [comment]
Finally, I have one problem left unsolved. that is,  the detection precision decreases because i replace the code.

```
old = Imgcodecs.imread(imgPath);
Imgproc.resize(old, frame, new Size(640, 640));
img = ImageFactory.getInstance().fromImage(HighGui.toBufferedImage(frame));
results = this.predictor.predict(img);
```

replace the above code with the following:

```
old = ImageFactory.getInstance().fromFile(Paths.get(imgPath));
img = old.resize(640, 640, true);
results = this.predictor.predict(img);
```

I think the drop in precision is because OpenCV reads images in _**BGR**_ format, while ImageFactory.getInstance().fromFile reads images in **RGB** format. Is my guess correct? Do you have a solution?
@frankfliu

**Comment by frankfliu** [comment]
@AndyDPesspd 
If you use DJL's OpenCV extension, ImageFactory will use OpenCV, and it will handle BGR properly: https://github.com/deepjavalibrary/djl/blob/master/extensions/opencv/src/main/java/ai/djl/opencv/OpenCVImage.java#L138

When you use `.optSynsetArtifactName("result.names")`, DJL will read this file as the text file, and each line be treated as a classification. It looks like your "result.names" is binary file and lacking \n and line feed.

**Comment by AndyDPesspd** [comment]
![image](https://github.com/deepjavalibrary/djl/assets/147293075/3e507e7b-3526-4053-b85e-dbd72487cfed)

You're right. If i add an OpenCV extension, the accuracy will return to normal. However,  a memory leak will occur again. I've done a lot of experiments to prove this, as shown in the table above. The conclusion is, with OpenCV . (whether OpenCV compiled by myself or DJL OpenCV extension) Memory leakage occurs. If OpenCV is not used, the precision is reduced. I don't know if you can come to that conclusion, but I've done a lot of experiments at this moment. So can you help me, is there a solution, neither memory leaks nor precision degradation? thank you very much @frankfliu

**Comment by AndyDPesspd** [comment]
> > @AndyDPesspd
> > I tried with DJL OpenCV extension. no memory leak as well. So the memory leak must related to your OpenCV code somewhere.
> > Can you elaborate a bit more about `translator.optSynsetArtifactName()`? What the problem are you facing? In our test we get the exact the same result no matter use OpenCV or not.
> 
> Yes, the OpenCV is compiled by myself. When i remove the OpenCV, no more memory leaks. And If.optSynsetArtifactName("result.names") is used, an empty array may be output, as shown in the preceding figure.

@frankfliu Can you show me your code？How do you use the OpenCV extension?  I added the OpenCV extension to the pom. and only used these three lines of code.  
```
old = ImageFactory.getInstance().fromFile(Paths.get(imgPath));
img = old.resize(640, 640, true);
results = this.predictor.predict(img);

```

No more action, but it does have a memory leak. Is my code missing a critical step? Can you show me yours?

**Comment by frankfliu** [comment]
If you use built-in Yolov5 model from DJL model zoo, you don't need resize the image.

The code I posted earlier can use OpenCV extension. You only need add opencv extension in the `pom.xml`. DJL will pick it up automatically. You can check the Image type, it should be an instance of `OpenCVImage`.

**Comment by AndyDPesspd** [comment]
> If you use built-in Yolov5 model from DJL model zoo, you don't need resize the image.
> 
> The code I posted earlier can use OpenCV extension. You only need add opencv extension in the `pom.xml`. DJL will pick it up automatically. You can check the Image type, it should be an instance of `OpenCVImage`.

I tried to enter the image directly, and the following error was reported.
```
RuntimeError: The size of tensor a (684) must match the size of tensor b (80) at non-singleton dimension 3

	at ai.djl.pytorch.jni.PyTorchLibrary.moduleRunMethod(Native Method)
	at ai.djl.pytorch.jni.IValueUtils.forward(IValueUtils.java:53)
	at ai.djl.pytorch.engine.PtSymbolBlock.forwardInternal(PtSymbolBlock.java:145)
	at ai.djl.nn.AbstractBaseBlock.forward(AbstractBaseBlock.java:79)
	at ai.djl.nn.Block.forward(Block.java:127)
	at ai.djl.inference.Predictor.predictInternal(Predictor.java:140)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:180)
	... 3 more
```
To check whether the resize function is normal, I put 640 * 640 pictures directly instead of resize. However, it is still a memory leak. I can confirm that the memory leak is caused by openCV. Can you give me some advice on how to skip openCV, such as how to handle the native BufferedImage and make it a BGR format? Or does ONNX have a Yolo V5 running template, is it worth trying? Thank you very much! @frankfliu

**Comment by AndyDPesspd** [comment]
Thank you very much. You've been a great help. Thank you for developing DJL, a tool that allows us to deploy algorithms on many devices. According to your code above, there is no memory leak or precision degradation. I think that's a very good question to think about, my last version of code is concise and standard, where is the problem? I'll continue to follow up and hope to explore why.

And there's a small problem to be concerned about. Considering your last suggestion：
**_“DJL will read this file as the text file, and each line be treated as a classification. It looks like your "result.names" is binary file and lacking \n and line feed.”_**

I provided the txt file to replace the binary file, as shown in the following figure. 
![image](https://github.com/deepjavalibrary/djl/assets/147293075/4418b81f-fc52-41a4-8be4-e489bafb18a8)

However, the problem of returning an empty array still occurs. Do you have any suggestions?

![image](https://github.com/deepjavalibrary/djl/assets/147293075/2d7cf20f-8ea9-4b5b-8073-d416ba948b04)

**Comment by frankfliu** [comment]
@AndyDPesspd 

Can you share your `synset.txt` file? You can debug the SynsetLoader code and see why you get this text:
https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java#L305

**Comment by AndyDPesspd** [comment]
> @AndyDPesspd
> 
> Can you share your `synset.txt` file? You can debug the SynsetLoader code and see why you get this text: https://github.com/deepjavalibrary/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java#L305



@frankfliu Here is my txt file. 


[synset.txt](https://github.com/deepjavalibrary/djl/files/13049408/synset.txt)

**Comment by frankfliu** [comment]
@AndyDPesspd 

The sysnset.txt looks fine. Can you create a mini reproduce project that I can test it?

If you only have two classes, you can just set classes directly:

```
        YoloV5Translator translator = YoloV5Translator.builder()
                .addTransform(new Resize(640, 640))
                .optRescaleSize(640, 640)
                .optApplyRatio(true)
                .optThreshold(0.4f)
                .optSynset(Arrays.asList("normal", "defect"))
                .build();
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optModelPath(path)
                .optTranslator(translator)
                .optEngine("PyTorch")
                .build();
```

**Comment by AndyDPesspd** [comment]
> @AndyDPesspd
> 
> The sysnset.txt looks fine. Can you create a mini reproduce project that I can test it?
> 
> If you only have two classes, you can just set classes directly:
> 
> ```
>         YoloV5Translator translator = YoloV5Translator.builder()
>                 .addTransform(new Resize(640, 640))
>                 .optRescaleSize(640, 640)
>                 .optApplyRatio(true)
>                 .optThreshold(0.4f)
>                 .optSynset(Arrays.asList("normal", "defect"))
>                 .build();
>         Criteria<Image, DetectedObjects> criteria = Criteria.builder()
>                 .setTypes(Image.class, DetectedObjects.class)
>                 .optModelPath(path)
>                 .optTranslator(translator)
>                 .optEngine("PyTorch")
>                 .build();
> ```

@frankfliu 

That's my initial code. However, memory leakage occurs when oepnCV is used when this Translator is used. If openCV is not used, the precision decreases. Okay, I'll try to understand SynsetLoader from the source code and debug it, thanks.

**Comment by AndyDPesspd** [comment]
> > @AndyDPesspd
> > The sysnset.txt looks fine. Can you create a mini reproduce project that I can test it?
> > If you only have two classes, you can just set classes directly:
> > ```
> >         YoloV5Translator translator = YoloV5Translator.builder()
> >                 .addTransform(new Resize(640, 640))
> >                 .optRescaleSize(640, 640)
> >                 .optApplyRatio(true)
> >                 .optThreshold(0.4f)
> >                 .optSynset(Arrays.asList("normal", "defect"))
> >                 .build();
> >         Criteria<Image, DetectedObjects> criteria = Criteria.builder()
> >                 .setTypes(Image.class, DetectedObjects.class)
> >                 .optModelPath(path)
> >                 .optTranslator(translator)
> >                 .optEngine("PyTorch")
> >                 .build();
> > ```
> 
> @frankfliu
> 
> That's my initial code. However, memory leakage occurs when oepnCV is used when this Translator is used. If openCV is not used, the precision decreases. Okay, I'll try to understand SynsetLoader from the source code and debug it, thanks.



> @AndyDPesspd
> 
> The sysnset.txt looks fine. Can you create a mini reproduce project that I can test it?
> 
> If you only have two classes, you can just set classes directly:
> 
> ```
>         YoloV5Translator translator = YoloV5Translator.builder()
>                 .addTransform(new Resize(640, 640))
>                 .optRescaleSize(640, 640)
>                 .optApplyRatio(true)
>                 .optThreshold(0.4f)
>                 .optSynset(Arrays.asList("normal", "defect"))
>                 .build();
>         Criteria<Image, DetectedObjects> criteria = Criteria.builder()
>                 .setTypes(Image.class, DetectedObjects.class)
>                 .optModelPath(path)
>                 .optTranslator(translator)
>                 .optEngine("PyTorch")
>                 .build();
> ```

@frankfliu Thank you very much.
I've figured out why, but I don't know how to change it, because that's your default setting.

If you jump inside the SynsetLoader, the following method is actually called：

`model.getArtifact(synsetFileName, Utils::readLines)`

However， `readLines(is, false)` method is used by default. 

And because “trim parameter == False” in readLines,  blank lines are counted according to the notes.

![image](https://github.com/deepjavalibrary/djl/assets/147293075/e30597aa-c4c7-41dd-a526-819e0ed0fc2c)


So the question is, how do you change your default settings?
