### ISSUE TITLE
java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by akumaigorodski** [deepjavalibrary/djl#2816]
## Description
I get this exception when preparing features for training, apparently there's an internal `DoubleBuffer` limit which my data size exceeds, but system monitor is showing that at most 46Gb of RAM is used while running this code while my system has 128Gb of RAM.

### Expected Behavior
No exception is expected.

### Error Message
```
java.nio.BufferOverflowException
	at java.base/java.nio.DirectDoubleBufferU.put(DirectDoubleBufferU.java:409)
	at java.base/java.nio.DirectDoubleBufferU.put(DirectDoubleBufferU.java:388)
	at ai.djl.ndarray.BaseNDManager.copyBuffer(BaseNDManager.java:484)
	at ai.djl.pytorch.engine.PtNDManager.create(PtNDManager.java:76)
	at ai.djl.pytorch.engine.PtNDManager.create(PtNDManager.java:31)
	at ai.djl.ndarray.NDManager.create(NDManager.java:498)
	at ai.djl.ndarray.NDManager.create(NDManager.java:437)
	at fovea.utils.Common$.featuresToNDArray(Common.scala:35)
	at maker.nn.spike.TrainerActor$$anonfun$receive$1.applyOrElse(TrainerActor.scala:51)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at maker.nn.spike.TrainerActor.aroundReceive(TrainerActor.scala:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

## How to Reproduce?
It seems it suffices to call `manager.create` with large enough `Array[Array[Double]]` to get an exception.

```scala
  def featuresToNDArray(features: List[SerialObservations], targetShape: Shape, manager: NDManager): (NDArray, NDArray) = {
    val (splitFeatures: Seq[Array[Double]], splitValues: Seq[Double]) = Random.shuffle(features).map(container => container.features.flatten -> container.value).unzip
    // Exception happens on the next line when calling `manager.create`
    val finalFeatures: NDArray = manager.create(splitFeatures.toArray).reshape(targetShape).toType(DataType.FLOAT32, false)
    val finalValues = manager.create(splitValues.toArray).toType(DataType.FLOAT32, false)
    (finalFeatures, finalValues)
  }
```

## Environment Info

I use SBT, not Gradle so I'm not sure what similar command I can execute, but at least my build.sbt is:
```
libraryDependencies += "ai.djl" % "api" % "0.22.1"

libraryDependencies += "ai.djl.pytorch" % "pytorch-engine" % "0.22.1"

libraryDependencies += "ai.djl.pytorch" % "pytorch-jni" % "2.0.1-0.23.0"
```

**Comment by frankfliu** [comment]
Java have 2G limits for array size. Are you trying to create a large NDArray that exceed 2G?
A few thing to consider:
1. Do you really need large NDArray?
2. Can you use Sparse tensor?
3. Can you create an empty NDArray, and set each dimension with smaller NDArray?

**Comment by akumaigorodski** [comment]
Thanks for the info, I've solved an issue by splitting prepared data into multiple chunks, then processing each of them individually and gradually merging into a resulting `NDArray`.
