### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class ai.djl.onnxruntime.engine.OrtNDManager

### ISSUE THREAD

**Issue by danieltog** [deepjavalibrary/djl#2838]
Hello!

I'm trying to run a Spring Boot project with DJL on Ubuntu 20 as a JAR file. I can run the project just fine, but when I try to make an inference I'm getting an error. I think it's because is not finding the Pytorch engine.

How to customize the Pytorch engine location?

```
### Error Message
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class ai.djl.onnxruntime.engine.OrtNDManager] with root cause

java.lang.NoClassDefFoundError: Could not initialize class ai.djl.onnxruntime.engine.OrtNDManager
	at ai.djl.onnxruntime.engine.OrtEngine.newBaseManager(OrtEngine.java:134) ~[onnxruntime-engine-0.24.0.jar!/:na]
	at ai.djl.onnxruntime.engine.OrtEngine.newModel(OrtEngine.java:122) ~[onnxruntime-engine-0.24.0.jar!/:na]
	at ai.djl.Model.newInstance(Model.java:99) ~[api-0.24.0.jar!/:na]
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:196) ~[api-0.24.0.jar!/:na]
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:159) ~[api-0.24.0.jar!/:na]
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172) ~[api-0.24.0.jar!/:na]
	at com.nvisual_djl.controller.InferenceController.predictCustomObjectOnnx(InferenceController.java:254) ~[classes!/:0.0.1-SNAPSHOT]
...
```

**Comment by danieltog** [comment]
I found the issue, it was because my server was blocking the internet, so it couldn't install the engine from the remote location
