### ISSUE TITLE
 Unsupported device: nc(0)

### ISSUE THREAD

**Issue by fafriat** [deepjavalibrary/djl#2858]
## Description
I am working on inf2.xlarge instance with Neuron devices

this is my code:

```java
Engine engine = Engine.getEngine("PyTorch");
Device device = Device.fromName("nc0", engine);
try (NDManager manager = NDManager.newBaseManager(device, "PyTorch")) {
```

### Expected Behavior

I should get a new NDManager instance.

### Error Message

```
java.lang.IllegalArgumentException: Unsupported device: nc(0)
	at ai.djl.pytorch.engine.PtDeviceType.toDeviceType(PtDeviceType.java:38) ~[pytorch-engine-0.24.0.jar:?]
	at ai.djl.pytorch.jni.JniUtils.createNdFromByteBuffer(JniUtils.java:167) ~[pytorch-engine-0.24.0.jar:?]
	at ai.djl.pytorch.engine.PtNDManager.create(PtNDManager.java:77) ~[pytorch-engine-0.24.0.jar:?]
	at ai.djl.pytorch.engine.PtNDManager.create(PtNDManager.java:31) ~[pytorch-engine-0.24.0.jar:?]
	at ai.djl.ndarray.NDManager.create(NDManager.java:498) ~[api-0.24.0.jar:?]
	at ai.djl.ndarray.NDManager.create(NDManager.java:571) ~[api-0.24.0.jar:?]
	at tech.solusoft.imagineai.SD15WF.lambda$run$0(SD15WF.java:129) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) [?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) [?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) [?:?]
	at tech.solusoft.imagineai.SD15WF.run(SD15WF.java:59) ~[?:?]
	at ai.djl.serving.workflow.Workflow$WorkflowExecutor.executeExpression(Workflow.java:316) ~[serving-0.24.0.jar:?]
	at ai.djl.serving.workflow.Workflow$WorkflowExecutor.execute(Workflow.java:290) ~[serving-0.24.0.jar:?]
	at ai.djl.serving.workflow.Workflow.execute(Workflow.java:167) ~[serving-0.24.0.jar:?]
	at ai.djl.serving.models.ModelManager.runJob(ModelManager.java:315) ~[serving-0.24.0.jar:?]
	at ai.djl.serving.http.InferenceRequestHandler.runJob(InferenceRequestHandler.java:282) [serving-0.24.0.jar:?]
	at ai.djl.serving.http.InferenceRequestHandler.predict(InferenceRequestHandler.java:274) [serving-0.24.0.jar:?]
	at ai.djl.serving.http.InferenceRequestHandler.handlePredictions(InferenceRequestHandler.java:164) [serving-0.24.0.jar:?]
	at ai.djl.serving.http.InferenceRequestHandler.handleRequest(InferenceRequestHandler.java:140) [serving-0.24.0.jar:?]
	at ai.djl.serving.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:49) [serving-0.24.0.jar:?]
	at ai.djl.serving.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:28) [serving-0.24.0.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [netty-codec-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [netty-codec-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) [netty-transport-classes-epoll-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [netty-transport-classes-epoll-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.99.Final.jar:4.1.99.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.99.Final.jar:4.1.99.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Any idea ?

**Comment by frankfliu** [comment]
@fafriat 
When youse neuron in DJL java mode, you should treat it as CPU. See our demo: https://github.com/deepjavalibrary/djl-demo/blob/master/aws/inferentia/src/main/java/com/example/inferentia/InferentiaDemo.java#L42-L47

It doesn't specify and device.

**Comment by fafriat** [comment]
@frankfliu This is what I did at first but I got another Exception: 
```
[33mWARN [m [92mBaseNDManager[m Input buffer size is greater than the NDArray size, please set limit explicitly.
terminate called without an active exception
/usr/local/bin/dockerd-entrypoint.sh: line 17:     8 Aborted                 (core dumped) /usr/bin/djl-serving "$@"
```

**Comment by fafriat** [comment]
Regarding your example, you get access to the NDManager from the Translator TranslatorContex, but in my case I am inside a Workflow Function.

**Comment by fafriat** [comment]
I investigated on the issue and added logs to understand where the problem is occurring as I have no stack or exception after the crash:


[32mINFO [m [92mSD15WF[m applyModel(): Before promptEncoded.getInput().getAsNDList(manager, 0)
[32mINFO [m [92mSD15WF[m applyModel(): promptEncoded.getInput(): Input:
Property Content-Type: tensor/ndlist
Content null: ai.djl.ndarray.BytesSupplierImpl@672b9453
[33mWARN [m [92mBaseNDManager[m Input buffer size is greater than the NDArray size, please set limit explicitly.
terminate called without an active exception
/usr/local/bin/dockerd-entrypoint.sh: line 17:     7 Aborted                 (core dumped) /usr/bin/djl-serving "$@"


The crash seems to appear on this call:

``
NDList result = promptEncoded.getInput().getAsNDList(manager, 0);
``
