### ISSUE TITLE
 Failed to load MXNet native library

### ISSUE THREAD

**Issue by Lenkense** [deepjavalibrary/djl#2878]
## Description
I'm trying to run TrainTicTacToe.java example. It used to work but for some reason is no longer working.

### Expected Behavior
After running the `main` method of training should start.

### Error Message
DEBUG Registering EngineProvider: MXNet
DEBUG Found default engine: MXNet
Exception in thread "main" ai.djl.engine.EngineException: Failed to load MXNet native library
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:77)
        at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:177)
        at ai.djl.engine.Engine.getInstance(Engine.java:132)
        at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:114)
        at com.cloudautoscaling.runableExamples.deepRL.TrainTicTacToe.runExample(TrainTicTacToe.java:70)
        at com.cloudautoscaling.runableExamples.deepRL.TrainTicTacToe.main(TrainTicTacToe.java:57)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String ai.djl.util.Utils.getEnvOrSystemProperty(java.lang.String)'
        at ai.djl.mxnet.jna.LibUtils.findOverrideLibrary(LibUtils.java:89)
        at ai.djl.mxnet.jna.LibUtils.getLibName(LibUtils.java:81)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:67)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:71)
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:53)
        ... 6 more

## What have you tried to solve it?

I have found many solution involving gradle but I'm using maven so I don't know how to adapt thos solutions. Additionally many solutions link to README.md files that no longer exist.

**Comment by frankfliu** [comment]
`java.lang.NoSuchMethodError`, this is most likely you are using a mismatched DJL API and MXNet engine library.

You can use BOM to avoid versioning issue: https://docs.djl.ai/bom/index.html
