### ISSUE TITLE
linux环境中提示Failed to download PaddlePaddle native library,是什么问题

### ISSUE THREAD

**Issue by mengxiangyu-png** [deepjavalibrary/djl#2939]
## Description
我试了另一个linux内核的openEuler release 22.03 (LTS-SP1)系统,去试验下paddleclas的demo,
执行的命令为 java -jar paddledjl-demo.jar ../89-inference-clas.zip ../1.jpg
报错提示如下，请问这个是环境问题，还是我demo本身的问题
java -jar paddledjl-demo.jar /home/mengxiangyu/djl/89-inference-clas.zip /home/mengxiangyu/djl/1.jpg
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ai.djl.paddlepaddle.engine.PpEngineProvider.getEngine(PpEngineProvider.java:36)
	at ai.djl.engine.Engine.getEngine(Engine.java:190)
	at ai.djl.Model.newInstance(Model.java:99)
	at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:196)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:159)
	at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
	at ai.djl.paddle.PaddleClasDsms.getModelAndClassifierFromLocal(PaddleClasDsms.java:42)
	at ai.djl.paddle.PaddleClasDsms.main(PaddleClasDsms.java:198)
Caused by: java.lang.IllegalStateException: Failed to download PaddlePaddle native library
	at ai.djl.paddlepaddle.jni.LibUtils.downloadLibrary(LibUtils.java:333)
	at ai.djl.paddlepaddle.jni.LibUtils.findLibraryInClasspath(LibUtils.java:197)
	at ai.djl.paddlepaddle.jni.LibUtils.loadLibrary(LibUtils.java:64)
	at ai.djl.paddlepaddle.engine.PpEngine.newInstance(PpEngine.java:43)
	at ai.djl.paddlepaddle.engine.PpEngineProvider$InstanceHolder.<clinit>(PpEngineProvider.java:40)
	... 8 more
Caused by: java.net.UnknownHostException: publish.djl.ai
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at ai.djl.util.Utils.openUrl(Utils.java:488)
	at ai.djl.util.Utils.openUrl(Utils.java:472)
	at ai.djl.paddlepaddle.jni.LibUtils.downloadLibrary(LibUtils.java:293)
	... 12 more

**Comment by mengxiangyu-png** [comment]
自己的打包方式出现问题，有些包没打进去造成的
