### ISSUE TITLE
RuntimeError: The size of tensor a (16) must match the size of tensor b (80) at non-singleton dimension 3

### ISSUE THREAD

**Issue by StreakerHan** [deepjavalibrary/djl#2964]
## pom.xml
~~~java
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.fly</groupId>
    <artifactId>ai-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>ai-service</name>
    <description>ai-service</description>
    <properties>
        <java.version>11</java.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ai.djl</groupId>
                <artifactId>bom</artifactId>
                <version>0.25.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.paddlepaddle</groupId>
            <artifactId>paddlepaddle-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-model-zoo</artifactId>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-cu118</artifactId>
            <version>2.0.1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-engine</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.tensorflow</groupId>
            <artifactId>tensorflow-engine</artifactId>
            <scope>runtime</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>ai.djl.onnxruntime</groupId>-->
<!--            <artifactId>onnxruntime-engine</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>ai.djl.onnxruntime</groupId>
            <artifactId>onnxruntime-engine</artifactId>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>alimaven</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>alimaven</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </pluginRepository>
    </pluginRepositories>
</project>
~~~

## java code
~~~shell
package com.fly.ai.yolo;

import ai.djl.Device;
import ai.djl.inference.Predictor;
import ai.djl.modality.cv.Image;
import ai.djl.modality.cv.ImageFactory;
import ai.djl.modality.cv.output.DetectedObjects;
import ai.djl.modality.cv.translator.YoloV5Translator;
import ai.djl.modality.cv.util.NDImageUtils;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDManager;
import ai.djl.ndarray.types.DataType;
import ai.djl.repository.zoo.Criteria;
import ai.djl.repository.zoo.ModelZoo;
import ai.djl.repository.zoo.ZooModel;
import ai.djl.translate.Translator;
import lombok.SneakyThrows;
import org.springframework.core.io.ClassPathResource;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.net.URI;
import java.net.URL;

import static java.awt.Image.SCALE_DEFAULT;

public class YoloTest {

    private static ZooModel<Image, DetectedObjects> yoloModel;

    @SneakyThrows
    public static void main(String[] args) {

        Device device = Device.gpu();

        Translator<Image, DetectedObjects> translator = YoloV5Translator
                .builder()
                .optThreshold(0.8f)
                .build();

        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                .setTypes(Image.class, DetectedObjects.class)
                .optDevice(device)
                .optModelUrls(getRealUrl("/model/tk/objDet.zip"))
                .optModelName("objDet.pt")
                .optTranslator(translator)
                .optEngine("PyTorch")
                .build();

        yoloModel = ModelZoo.loadModel(criteria);

        BufferedImage image = ImageIO.read(new URL("image url"));
        final BufferedImage scale = scale(image, 800, 800);
        Image img = ImageFactory.getInstance().fromImage(scale);
        Image scaledImage = scale(img, 800, 800);
        long startTime = System.currentTimeMillis();

        DetectedObjects detections;
        try (Predictor<Image, DetectedObjects> predictor = yoloModel.newPredictor()) {
            detections = predictor.predict(scaledImage);
        }
    }

    public static BufferedImage scale(BufferedImage original, int width, int height) {
        if (width == original.getWidth() && height == original.getHeight()) {
            return original;
        }

        java.awt.Image scaledInstance = original.getScaledInstance(width, height, SCALE_DEFAULT);
        BufferedImage scaledImage = new BufferedImage(width, height, original.getType());
        scaledImage.getGraphics().drawImage(scaledInstance, 0, 0, null);
        return scaledImage;
    }

    public static Image scale(Image original, int width, int height) {
        if (width == original.getWidth() && height == original.getHeight()) {
            return original;
        }

        try(NDManager manager = NDManager.newBaseManager()) {
            NDArray ndArray = original.toNDArray(manager);
            NDArray resize = NDImageUtils.resize(ndArray, width, height, Image.Interpolation.BILINEAR);
            resize = resize.toType(DataType.INT8, false);
            return ImageFactory.getInstance().fromNDArray(resize);
        }
    }

    @SneakyThrows
    public static String getRealUrl(String name) {
        if (name.startsWith("http") || name.startsWith("file:")) {
            return name;
        }

        URI uri = new ClassPathResource(name).getURI();
        if (uri.toString().startsWith("jar:")) {
            return "jar://" + name;
        }

        return uri.toString();
    }
}

~~~

## The above code runs in a Docker environment, with pytorch 2.0.1+cuda11.8. Unfortunately, he made an error in his reasoning, and the error message is as follows
~~~bash
2024-01-25 15:50:16 RuntimeError: The size of tensor a (16) must match the size of tensor b (80) at non-singleton dimension 3
2024-01-25 15:50:16 
2024-01-25 15:50:16     at ai.djl.pytorch.jni.PyTorchLibrary.moduleRunMethod(Native Method) ~[pytorch-engine-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.pytorch.jni.IValueUtils.forward(IValueUtils.java:57) ~[pytorch-engine-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.pytorch.engine.PtSymbolBlock.forwardInternal(PtSymbolBlock.java:145) ~[pytorch-engine-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.nn.AbstractBaseBlock.forward(AbstractBaseBlock.java:79) ~[api-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.nn.Block.forward(Block.java:127) ~[api-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.inference.Predictor.predictInternal(Predictor.java:144) ~[api-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.inference.Predictor.batchPredict(Predictor.java:184) ~[api-0.25.0.jar!/:na]
2024-01-25 15:50:16     at ai.djl.inference.Predictor.predict(Predictor.java:130) ~[api-0.25.0.jar!/:na]
2024-01-25 15:50:16     at com.fly.ai.yolo.YoloService.detect(YoloService.java:107) ~[classes!/:0.0.1-SNAPSHOT]
2024-01-25 15:50:16     at com.fly.ai.yolo.YoloService.detect(YoloService.java:89) ~[classes!/:0.0.1-SNAPSHOT]
2024-01-25 15:50:16     at com.fly.ai.yolo.YoloService.getResultImage(YoloService.java:127) ~[classes!/:0.0.1-SNAPSHOT]
2024-01-25 15:50:16     at com.fly.ai.yolo.YoloController.ocr(YoloController.java:40) ~[classes!/:0.0.1-SNAPSHOT]
2024-01-25 15:50:16     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-01-25 15:50:16     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
2024-01-25 15:50:16     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-01-25 15:50:16     at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
2024-01-25 15:50:16     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.16.jar!/:5.3.16]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.58.jar!/:na]
2024-01-25 15:50:16     at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
~~~

I really hope you can help me solve this problem.

**Comment by frankfliu** [comment]
I noticed you resized the model to 800x800, is your model expect this input size?

`YoloV5Translator` default will resize image to 640x640, can try the following:

```
        Criteria<Image, DetectedObjects> criteria = Criteria.builder()
                         .setTypes(Image.class, DetectedObjects.class)
                        .optDevice(device)
                        .optModelUrls(getRealUrl("/model/tk/objDet.zip"))
                        .optModelName("objDet.pt")
                        .optEngine("PyTorch")
                        .optArgument("width", 800)
                        .optArgument("height", 800)
                        .optArgument("resize", true)
                        .optArgument("toTensor", true)
                        .optArgument("applyRatio", true)
                        .optArgument("threshold", 0.8f)
                        .optTranslatorFactory(new YoloV5TranslatorFactory())
                        .build();

```
