### ISSUE TITLE
Unzip large file raise ArithmeticException integer overflow

### ISSUE THREAD

**Issue by oreo-yum** [deepjavalibrary/djl#3073]
## Description
Unzip large file raise ArithmeticException integer overflow. Try to follow [Chatbot example]( https://github.com/deepjavalibrary/djl-demo/blob/master/huggingface/nlp/src/main/java/com/examples/Chatbot.java) to load a real large llama model for llama.cpp engine (llama-2-7b-chat.Q5_K_S.gguf 4.65G). As there is no such model in model zoo, I use internal HDFS space to store the model in zip format.

It throws ArithmeticException in ValidationInputStream.validate when build model, it seems to cast a long to int but it's out of the range of int. It seems the core part of the issue is `ZipUtils.unzip`, and it could be reproduced out of the model building scenario.

the unzip works fine with smaller size llama gguf file (e.g., llama-2-7b-chat.Q2_K.gguf, 2.83G).

### Expected Behavior
unzip large file without exception

### Error Message

```
Exception in thread "main" java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at ai.djl.util.ZipUtils$ValidationInputStream.findEND(ZipUtils.java:246)
	at ai.djl.util.ZipUtils$ValidationInputStream.initCEN(ZipUtils.java:267)
	at ai.djl.util.ZipUtils$ValidationInputStream.validate(ZipUtils.java:192)
	at ai.djl.util.ZipUtils.unzip(ZipUtils.java:74)
	at my.test.Unzip.main(Unzip.java:12)
```

### Steps to reproduce

- download llama-2-7b-chat.Q5_K_S.gguf in https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/tree/main
- zip llama-2-7b-chat.Q5_K_S.gguf to llama-2-7b-chat.Q5_K_S.gguf.zip
```java
package my.test
import ai.djl.util.ZipUtils;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class Unzip {
    public static void main(String[] args) throws IOException {
        ZipUtils.unzip(
                Files.newInputStream(new File("./llama-2-7b-chat.Q5_K_S.gguf.zip").toPath()),
                        new File("./llama-2-7b-chat.Q5_K_S").toPath()
                );
    }
}
```

- run above code

## Environment Info
djl 0.26
el7.x86_64

**Comment by oreo-yum** [comment]
Thanks for your quick fix, it works for me.
