### ISSUE TITLE
PyTorch engine does not support centos7.9

### ISSUE THREAD

**Issue by leleZeng** [deepjavalibrary/djl#3090]
## Description
Similar to another issue

[libstdc++.so.6: version `CXXABI_1.3.9' not found by sentencepiece](https://github.com/deepjavalibrary/djl/issues/2400)

An exception occurred while running the pytorch model on Centos7.9, but it ran normally on Windows 10.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'whisperModel' defined in URL [jar:file:/opt/server/ess/ess-facade-1.0-SNAPSHOT.jar!/BOOT-INF/lib/ess-biz-1.0-SNAPSHOT.jar!/com/gotion/ess/biz/ai/inference/whisper/WhisperModel.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gotion.ess.biz.ai.inference.whisper.WhisperModel]: Constructor threw exception; nested exception is ai.djl.engine.EngineException: Failed to load PyTorch native library
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1316)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1153)
        at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:87)
        at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterSingletonsInstantiated(XxlJobSpringExecutor.java:38)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144)
        at com.gotion.core.boot.GotionApplication.run(GotionApplication.java:36)
        at com.gotion.ess.EssApplication.main(EssApplication.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gotion.ess.biz.ai.inference.whisper.WhisperModel]: Constructor threw exception; nested exception is ai.djl.engine.EngineException: Failed to load PyTorch native library
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1308)
        ... 29 common frames omitted
Caused by: ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:90)
        at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:41)
        at ai.djl.engine.Engine.getEngine(Engine.java:190)
        at ai.djl.Model.newInstance(Model.java:99)
        at ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:196)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:159)
        at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:172)
        at com.gotion.ess.biz.ai.inference.whisper.WhisperModel.<init>(WhisperModel.java:50)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212)
        ... 31 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /root/.djl.ai/pytorch/2.1.2-cpu-linux-x86_64/libc10.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/.djl.ai/pytorch/2.1.2-cpu-linux-x86_64/libc10.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2635)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1850)
        at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:379)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:170)
        at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:82)
        at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53)
        ... 43 common frames omitted

```

**Comment by frankfliu** [comment]
You should use precxx11 version of PyTorch for centos:7

```
export PYTORCH_PRECXX11=true
```

**Comment by leleZeng** [comment]
Thank you very much, the configuration has taken effect.
