### ISSUE TITLE
UnsatisfiedLinkError: 'boolean ai.djl.pytorch.jni.PyTorchLibrary.torchIsContiguous(long)'

### ISSUE THREAD

**Issue by david-sitsky** [deepjavalibrary/djl#3194]
## Description

I am using:

ai.djl.pytorch:pytorch-engine:0.28.0-SNAPSHOT
ai.djl.pytorch:pytorch-jni:2.2.2-0.28.0-SNAPSHOT
ai.djl.pytorch:pytorch-native-cpu:2.2.2:linux-x86_64

My program has started to just fail given an update from snapshot.  This seems related to this PR: https://github.com/deepjavalibrary/djl/pull/3137 which has added a method to PyTorchLibrary.torchIsContiguous() which was merged recently.

```
java.lang.UnsatisfiedLinkError: 'boolean ai.djl.pytorch.jni.PyTorchLibrary.torchIsContiguous(long)'
        at ai.djl.pytorch.jni.PyTorchLibrary.torchIsContiguous(Native Method) ~[pytorch-engine-0.28.0-SNAPSHOT.jar:?]
        at ai.djl.pytorch.jni.JniUtils.getByteBuffer(JniUtils.java:1682) ~[pytorch-engine-0.28.0-SNAPSHOT.jar:?]
        at ai.djl.pytorch.engine.PtNDArray.toByteBuffer(PtNDArray.java:233) ~[pytorch-engine-0.28.0-SNAPSHOT.jar:?]
        at ai.djl.ndarray.NDArray.toFloatArray(NDArray.java:277) ~[api-0.28.0-SNAPSHOT.jar:?]
...
        at ai.djl.inference.Predictor.batchPredict(Predictor.java:190) ~[api-0.28.0-SNAPSHOT.jar:?]
        at ai.djl.inference.Predictor.predict(Predictor.java:132) ~[api-0.28.0-SNAPSHOT.jar:?]
```

I suspect this is related to what GitHub actions have run and perhaps what is still pending?  I thought I'd report it just in case.

Is there a way to order the actions to prevent this from happening in the future?

**Comment by frankfliu** [comment]
There a some jni code change recently. Please remove cache and refresh the dependencies

**Comment by david-sitsky** [comment]
My apologies.. I had an errand `PYTORCH_LIBRARY_PATH` setting in place pointing to an older version.  Once that was removed all looked fine again.

I read 0.28.0 is planned to be released sometime in May?  Is that looking likely?  I'll hoping to move off snapshots soon.. :)
