### ISSUE TITLE
TimeSeries API Frequency

### ISSUE THREAD

**Issue by keklol5050** [deepjavalibrary/djl#3271]
If we specify the frequency as required by the Lag class or as the GluonTS documentation says,
![image](https://github.com/deepjavalibrary/djl/assets/158003379/ff34d367-8ebc-401f-90e4-5b52d7e1d11f)
for example "1H", "H", "15min", we will get an exception:
`Exception in thread "main" java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.base/java.time.Duration.parse(Duration.java:419)
	at ai.djl.timeseries.transform.feature.Feature.addTimeFeature(Feature.java:127)
	at ai.djl.timeseries.transform.feature.Feature.addTimeFeature(Feature.java:75)
	at ai.djl.timeseries.transform.feature.AddTimeFeature.transform(AddTimeFeature.java:63)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.apply(TimeSeriesDataset.java:105)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.get(TimeSeriesDataset.java:60)
	at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:170)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:145)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:43)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:54)`
or 
`Exception in thread "main" java.time.format.DateTimeParseException: Text cannot be parsed to a Period
	at java.base/java.time.Period.parse(Period.java:349)
	at ai.djl.timeseries.transform.feature.Feature.addTimeFeature(Feature.java:129)
	at ai.djl.timeseries.transform.feature.Feature.addTimeFeature(Feature.java:75)
	at ai.djl.timeseries.transform.feature.AddTimeFeature.transform(AddTimeFeature.java:63)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.apply(TimeSeriesDataset.java:105)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.get(TimeSeriesDataset.java:60)
	at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:170)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:145)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:43)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:54)`

if we specify the frequency in the format required by the Period and Duration classes (for example "1h", "5h") we will receive an exception from DJL:
Exception in thread "main" java.lang.IllegalArgumentException: invalid frequency
	at ai.djl.timeseries.timefeature.Lag.getLagsForFreq(Lag.java:90)
	at ai.djl.timeseries.timefeature.Lag.getLagsForFreq(Lag.java:118)
	at ai.djl.timeseries.model.deepar.DeepARNetwork.<init>(DeepARNetwork.java:127)
	at ai.djl.timeseries.model.deepar.DeepARTrainingNetwork.<init>(DeepARTrainingNetwork.java:26)
	at ai.djl.timeseries.model.deepar.DeepARNetwork$Builder.buildTrainingNetwork(DeepARNetwork.java:608)

if we specify the frequency like "15M" = it will be 15 months, so with weeks and months everything is ok

**Comment by keklol5050** [comment]
also, in gluonTS cardinality can be "auto" or "ignore", if we dont use categorical features, but TimeSeries API docs doesnt indicate how can we do the same thing here

**Comment by keklol5050** [comment]
also, in gluonTS we can make context length and prediction length different, but when i try to do it in TimeSeries API i get exception in any case, regardless of the length of the time series:

`Exception in thread "main" ai.djl.translate.TranslateException: java.lang.IllegalArgumentException: lags cannot go further than prior sequence length, found lag 157 while prior sequence is only 156-long
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:196)
	at com.crypto.analysis.main.ex.dar.TrainTimeSeries.predict(TrainTimeSeries.java:154)
	at com.crypto.analysis.main.ex.dar.TrainTimeSeries.main(TrainTimeSeries.java:64)
Caused by: java.lang.IllegalArgumentException: lags cannot go further than prior sequence length, found lag 157 while prior sequence is only 156-long
	at ai.djl.timeseries.model.deepar.DeepARNetwork.laggedSequenceValues(DeepARNetwork.java:267)
	at ai.djl.timeseries.model.deepar.DeepARNetwork.unrollLaggedRnn(DeepARNetwork.java:233)
	at ai.djl.timeseries.model.deepar.DeepARPredictionNetwork.forwardInternal(DeepARPredictionNetwork.java:47)
	at ai.djl.nn.AbstractBaseBlock.forward(AbstractBaseBlock.java:79)
	at ai.djl.nn.Block.forward(Block.java:127)
	at ai.djl.inference.Predictor.predictInternal(Predictor.java:146)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:187)
	... 2 more`
	
that is TrainTimeSeries.class from examples with some changes:

` M5Forecast.Builder builder =
                M5Forecast.builder()
                        .optUsage(usage)
                        .optRepository(BasicDatasets.REPOSITORY)
                        .optGroupId(BasicDatasets.GROUP_ID)
                        .optArtifactId("m5forecast-unittest")
                        .setTransformation(transformation)
                        .setContextLength(8) // here changed
                        .setSampling(32, usage == Dataset.Usage.TRAIN);`
`DeepARNetwork.Builder builder =
                DeepARNetwork.builder()
                        .setCardinality(cardinality)
                        .setFreq(freq)
                        .setPredictionLength(4)// here changed
                        .optContextLength(8)// here changed
                        .optDistrOutput(distributionOutput)
                        .optUseFeatStaticCat(true);`
` Map<String, Object> arguments = new ConcurrentHashMap<>();
            arguments.put("prediction_length", 4);
            arguments.put("context_length", 8; // added contextlength param`
`  inputShapes[6] = new Shape(1, 8, TimeFeature.timeFeaturesFromFreqStr(freq).size() + 1);
                inputShapes[7] = new Shape(1, 8);
                inputShapes[8] = new Shape(1, 8);`

**Comment by keklol5050** [comment]
![image](https://github.com/deepjavalibrary/djl/assets/158003379/4b7c5bdd-9568-42d0-8e47-f70aee798a41)
i think problem is here, bec for Duration.class we need PT, not only P, like PT1H

**Comment by keklol5050** [comment]
also got a strange exception when 
```
                        .optUseFeatStaticCat(false)
                        .optUseFeatStaticReal(false)
                        .optUseFeatDynamicReal(true)

                   ...
    @Override
        public TimeSeriesData getTimeSeriesData(NDManager manager, long index) {
            float[][] ts = timeSeries.get((int) index);

            TimeSeriesData data = new TimeSeriesData(ts.length);

            data.add(FieldName.TARGET, manager.create(ts[targetPosition]));
           
            for (int i = 0; i < ts.length; i++) {
                if (targetPosition.contains(i)) continue;
                data.add(FieldName.FEAT_DYNAMIC_REAL, manager.create(ts[i]));
            }

            data.setStartTime(dates.get((int) index).toInstant().atZone(ZoneId.of("UTC+0")).toLocalDateTime());
            return data;
        }
```

```
Exception in thread "main" java.lang.IllegalArgumentException: FEAT_STATIC_REAL don't map to any NDArray
	at ai.djl.timeseries.transform.convert.Convert.asArray(Convert.java:89)
	at ai.djl.timeseries.transform.convert.AsArray.transform(AsArray.java:56)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.apply(TimeSeriesDataset.java:105)
	at ai.djl.timeseries.dataset.TimeSeriesDataset.get(TimeSeriesDataset.java:60)
	at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:170)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:145)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:43)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:54)
```

in gluonTS feat_dynamic_real can be used without static_real

**Comment by keklol5050** [comment]
problem with lags here https://github.com/deepjavalibrary/djl/blob/master/extensions/timeseries/src/main/java/ai/djl/timeseries/translator/BaseTimeSeriesTranslator.java
![image](https://github.com/deepjavalibrary/djl/assets/158003379/52279907-8d40-4bfd-b37e-bef7ed718750)

**Comment by keklol5050** [comment]
@frankfliu also DeepARNetwork class has a few strange lines of code like TRAIN_INPUT_FIELDS or this
![image](https://github.com/deepjavalibrary/djl/assets/158003379/3da19d25-5642-4c3a-8931-fad0127d8dfb)
