### ISSUE TITLE
get error when run FeatureExtraction

### ISSUE THREAD

**Issue by yanchaoguo** [deepjavalibrary/djl#897]
本地已下载，但无法加载dll库，错误如下：

Exception in thread "main" ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:58)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
	at ai.djl.engine.Engine.getEngine(Engine.java:152)
	at ai.djl.engine.Engine.getInstance(Engine.java:117)
	at ai.djl.examples.inference.face.FeatureExtraction.main(FeatureExtraction.java:47)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\bigdata\.djl.ai\pytorch\1.6.0-cu102-win-x86_64\0.11.0-SNAPSHOT-cu102-djl_torch.dll: 找不到指定的程序。
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:344)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:77)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:46)
	... 4 more

**Comment by frankfliu** [comment]
@yanchaoguo 
DJL use JNI load pytorch native library, each version of DJL can only work with one specific PyTorch version.
DJL 0.11.0-SNAPSHOT can only work with pytorch 1.8.1,
DJL 0.10.0 can only work with pytorch 1.7.1

We need make it clear in our document. Working on a documentation improvement.

**Comment by frankfliu** [comment]
@yanchaoguo I updated pytorch document: https://github.com/deepjavalibrary/djl/pull/898
