### ISSUE TITLE
djl.ai\pytorch\1.8.1-cpu-win-x86_64\asmjit.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by mengpengfei** [deepjavalibrary/djl#962]
java.lang.UnsatisfiedLinkError: C:\Users\Administrator\.djl.ai\pytorch\1.8.1-cpu-win-x86_64\asmjit.dll: Can't find dependent libraries
		at java.lang.ClassLoader$NativeLibrary.load(Native Method)
		at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
		at java.lang.Runtime.load0(Runtime.java:809)
		at java.lang.System.load(System.java:1086)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
		at java.util.Iterator.forEachRemaining(Iterator.java:116)
		at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
		at ai.djl.pytorch.jni.LibUtils.loadWinDependencies(LibUtils.java:121)
		at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:75)
		at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:46)
		at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:40)
		at ai.djl.engine.Engine.getEngine(Engine.java:152)
		at ai.djl.engine.Engine.getInstance(Engine.java:117)
		at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:112)

**Comment by frankfliu** [comment]
Did you installed VC 2019 Redistributable packages?
See: http://docs.djl.ai/docs/development/troubleshooting.html#13-unsatisfiedlinkerror-issue
