### ISSUE TITLE
Is there a way of implement "djl.ndarray" only without any deep learning engine ?

### ISSUE THREAD

**Issue by Zhuxinpei** [deepjavalibrary/djl#966]
## Description

To some reason, all my program needed was the "ai.djl.ndarray" API to finish the N-dimension array reshape. Considersing there was always "Failed to load MXNet native library" error and no need for deep learning things. Is there a way of implement "djl.ndarray" only without any deep learning engine ? Thanks.

**Comment by frankfliu** [comment]
DJL rely on engine to achieve NDArray operation. For CPU machine, MXNet or PyTorch engine native is pretty small. The overhead of engine dependency is not that bad.

Can you tell me more about "Failed to load MXNet native library" error?
Which os are your running?
Can you run the following command and send the log:
```
cd djl
./gradlew debug
```

**Comment by Zhuxinpei** [comment]
Really thanks for your reply. I'm using Win10 Android Studio. The program take Bytebuffer from camera and I implemented djl.ndarray to split the 3-dimension array.

The dependencies as:
```
    implementation "ai.djl:api:0.11.0"
    implementation "org.slf4j:slf4j-api:1.7.30"
    implementation "org.slf4j:slf4j-simple:1.7.26"
    implementation "ai.djl.mxnet:mxnet-engine:0.11.0"
    runtimeOnly "ai.djl.mxnet:mxnet-native-auto:1.8.0" 
```

The code refer to dji.ndarray as:
```
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;

import ai.djl.ndarray.*;
import ai.djl.ndarray.types.*;
import ai.djl.ndarray.index.*;

public class PostProc {
    public static void pred_bbox_reorg(ByteBuffer pred_bbox){
        pred_bbox.rewind();
        FloatBuffer pred_bbox_temp1 = pred_bbox.asFloatBuffer();
        float[] pred_bbox_temp2 = new float[9 * 16 * 51];
        pred_bbox_temp1.get(pred_bbox_temp2);

        NDManager manager = NDManager.newBaseManager();
        NDArray pred_bbox_temp3 = manager.create(pred_bbox_temp2, new Shape(9,16,3,17));
        NDList pred_bbox_temp4 = pred_bbox_temp3.split(new long[]{2,2,1},-1);
        NDArray a = pred_bbox_temp4.get(0);
    }
}
```

When I run in a android device, the error log as:
```
I/android_camera: Rejecting re-init on previously-failed class java.lang.Class<com.sun.jna.Native>: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource path (.)
        at void com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath() (Native.java:1032)
        at void com.sun.jna.Native.loadNativeDispatchLibrary() (Native.java:988)
        at void com.sun.jna.Native.<clinit>() (Native.java:195)
        at com.sun.jna.Library com.sun.jna.Native.load(java.lang.String, java.lang.Class) (Native.java:570)
        at ai.djl.util.cuda.CudaLibrary ai.djl.util.cuda.CudaUtils.loadLibrary() (CudaUtils.java:181)
        at void ai.djl.util.cuda.CudaUtils.<clinit>() (CudaUtils.java:29)
        at int ai.djl.util.cuda.CudaUtils.getGpuCount() (CudaUtils.java:48)
        at ai.djl.util.Platform ai.djl.util.Platform.fromSystem() (Platform.java:89)
        at java.lang.String ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath() (LibUtils.java:122)
        at java.lang.String ai.djl.mxnet.jna.LibUtils.getLibName() (LibUtils.java:80)
        at ai.djl.mxnet.jna.MxnetLibrary ai.djl.mxnet.jna.LibUtils.loadLibrary() (LibUtils.java:64)
        at ai.djl.engine.Engine ai.djl.mxnet.engine.MxEngineProvider.getEngine() (MxEngineProvider.java:40)
        at ai.djl.engine.Engine ai.djl.engine.Engine.getEngine(java.lang.String) (Engine.java:152)
        at ai.djl.ndarray.NDManager ai.djl.ndarray.NDManager.newBaseManager() (NDManager.java:112)
E/AndroidRuntime: FATAL EXCEPTION: CameraThread
    Process: com.example.android_camera2, PID: 19803
    ai.djl.engine.EngineException: Failed to load MXNet native library
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:78)
        at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:40)
        at ai.djl.engine.Engine.getEngine(Engine.java:152)
        at ai.djl.engine.Engine.getInstance(Engine.java:117)
        at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:112)
        at com.example.android_camera2.PostProc.pred_bbox_reorg(PostProc.java:17)
        at com.example.android_camera2.MainActivity$4.onImageAvailable(MainActivity.java:356)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.NoClassDefFoundError: com.sun.jna.Native
        at com.sun.jna.Native.load(Native.java:590)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:71)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:69)
        at ai.djl.mxnet.jna.JnaUtils.getAllOpNames(JnaUtils.java:88)
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:52)
        at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:40) 
        at ai.djl.engine.Engine.getEngine(Engine.java:152) 
        at ai.djl.engine.Engine.getInstance(Engine.java:117) 
        at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:112) 
        at com.example.android_camera2.PostProc.pred_bbox_reorg(PostProc.java:17) 
        at com.example.android_camera2.MainActivity$4.onImageAvailable(MainActivity.java:356) 
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-aarch64/libjnidispatch.so) not found in resource path (.)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1032)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
        at com.sun.jna.Native.<clinit>(Native.java:195)
        at com.sun.jna.Native.load(Native.java:570)
        at ai.djl.util.cuda.CudaUtils.loadLibrary(CudaUtils.java:181)
        at ai.djl.util.cuda.CudaUtils.<clinit>(CudaUtils.java:29)
        at ai.djl.util.cuda.CudaUtils.getGpuCount(CudaUtils.java:48)
        at ai.djl.util.Platform.fromSystem(Platform.java:89)
        at ai.djl.mxnet.jna.LibUtils.findLibraryInClasspath(LibUtils.java:122)
        at ai.djl.mxnet.jna.LibUtils.getLibName(LibUtils.java:80)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:64)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:69) 
        at ai.djl.mxnet.jna.JnaUtils.getAllOpNames(JnaUtils.java:88) 
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:52) 
        at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:40) 
        at ai.djl.engine.Engine.getEngine(Engine.java:152) 
        at ai.djl.engine.Engine.getInstance(Engine.java:117) 
        at ai.djl.ndarray.NDManager.newBaseManager(NDManager.java:112) 
        at com.example.android_camera2.PostProc.pred_bbox_reorg(PostProc.java:17) 
        at com.example.android_camera2.MainActivity$4.onImageAvailable(MainActivity.java:356) 
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:800) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
I/Process: Sending signal. PID: 19803 SIG: 9
```

If you have any idea of anything wrong, please help, thanks!

**Comment by frankfliu** [comment]
@Zhuxinpei 
MXNet currently doesn't work on Android, you need to build your android native library manually.
But you can use PyTorch with DJL on Android: See: https://github.com/deepjavalibrary/djl-demo/tree/master/android/pytorch_android

**Comment by Zhuxinpei** [comment]
It works, thank you very much !
